#!/usr/bin/env node
// Generated by scaffold-solution — do not edit.
// Quality ratchet: counts of known debt classes may only go DOWN. The baseline
// lives in quality-ratchet.json (solution-owned — update it when you burn debt
// down). Wired into `pnpm verify`; a count above baseline fails the gate.
//
// lintWarnings (GG-17): the lint script deliberately omits --max-warnings 0
// because some rules (e.g. ADR-0017 max-lines) are warn-level on purpose, so
// a hard zero-cap would gate already-over-budget files that are out of scope
// for the change in flight. Instead this ratchet counts ESLint warnings and
// caps them at the committed baseline — new warnings fail the gate, existing
// warn-level debt does not, and the baseline can only be lowered, never raised
// without review.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SCAN_DIRS = ["app", "solution", "components", "lib"].filter((d) =>
  fs.existsSync(path.join(ROOT, d)),
);

function* walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name === ".next") continue;
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(abs);
    else if (/\.(tsx?|jsx?|css)$/.test(entry.name)) yield abs;
  }
}

function countEslintWarnings() {
  let out = "";
  try {
    out = execSync("eslint . --format json", { cwd: ROOT, encoding: "utf8", maxBuffer: 1024 * 1024 * 64 });
  } catch (err) {
    // ESLint exits 1 when errors are present — the JSON report is still on stdout.
    out = err.stdout?.toString() ?? "";
    if (!out) {
      console.warn("[ratchet] eslint run produced no output — skipping lintWarnings this run.");
      return 0;
    }
  }
  try {
    const results = JSON.parse(out);
    return results.reduce((sum, r) => sum + (r.warningCount ?? 0), 0);
  } catch {
    console.warn("[ratchet] could not parse eslint JSON output — skipping lintWarnings this run.");
    return 0;
  }
}

const counts = { orangeFills: 0, rawGrayClasses: 0, oversizeFiles: 0, lintWarnings: countEslintWarnings() };
for (const dir of SCAN_DIRS) {
  for (const file of walk(path.join(ROOT, dir))) {
    const src = fs.readFileSync(file, "utf8");
    // DQ design system: orange (--color-secondary / #FB5535) is an accent, never a fill.
    counts.orangeFills += (src.match(/bg-\[var\(--color-secondary\)\]|bg-\[#(?:FB5535|fb5535)\]/g) ?? []).length;
    // Raw Tailwind grays bypass the token system (allowlisted in globals.css only).
    if (!file.endsWith("globals.css")) {
      counts.rawGrayClasses += (src.match(/(?:^|["'\s])(?:bg|text|border)-gray-\d{2,3}/g) ?? []).length;
    }
    // Oversize applies to HAND-AUTHORED components only — generator-owned chrome
    // (header "Generated by scaffold-solution") is regenerated, not maintained here.
    if (
      /\.(tsx|jsx)$/.test(file) &&
      !src.slice(0, 400).includes("Generated by scaffold-solution") &&
      src.split("\n").length > 400
    ) {
      counts.oversizeFiles += 1;
    }
  }
}

const baselinePath = path.join(ROOT, "quality-ratchet.json");
if (!fs.existsSync(baselinePath)) {
  fs.writeFileSync(baselinePath, JSON.stringify(counts, null, 2) + "\n");
  console.log("[ratchet] no baseline found — wrote current counts as quality-ratchet.json");
  process.exit(0);
}
const baseline = JSON.parse(fs.readFileSync(baselinePath, "utf8"));
let failed = false;
for (const [key, value] of Object.entries(counts)) {
  const allowed = baseline[key] ?? 0;
  if (value > allowed) {
    console.error(`[ratchet] ${key}: ${value} > baseline ${allowed} — counts only go down. Fix the new debt or (exceptionally) raise the baseline with a review.`);
    failed = true;
  } else if (value < allowed) {
    console.log(`[ratchet] ${key}: ${value} < baseline ${allowed} — nice. Lower the baseline in quality-ratchet.json to lock it in.`);
  }
}
process.exit(failed ? 1 : 0);
