#!/usr/bin/env node
// Generated by scaffold-solution — do not edit.
// Env-drift gate (wired into `pnpm verify`): every process.env.X the app source
// reads must be declared in .env.example, so a fresh clone can always discover the
// full configuration surface. The generator derives .env.example from the manifest;
// this check catches drift from HAND-WRITTEN code adding undeclared reads.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
// Runtime-provided or framework-internal vars that never belong in .env.example.
const BUILTINS = new Set(["NODE_ENV", "NEXT_RUNTIME", "NEXT_PHASE", "PORT", "CI", "VERCEL", "VERCEL_ENV", "VERCEL_URL", "TZ"]);
const SCAN_DIRS = ["app", "solution", "components", "lib", "middleware.ts", "instrumentation.ts", "instrumentation.node.ts", "next.config.ts"]
  .map((d) => path.join(ROOT, d))
  .filter((d) => fs.existsSync(d));

function* walk(target) {
  const stat = fs.statSync(target);
  if (stat.isFile()) { yield target; return; }
  for (const entry of fs.readdirSync(target, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name === ".next") continue;
    const abs = path.join(target, entry.name);
    if (entry.isDirectory()) yield* walk(abs);
    else if (/\.(tsx?|jsx?|mjs)$/.test(entry.name)) yield abs;
  }
}

const declared = new Set();
const envExample = path.join(ROOT, ".env.example");
if (fs.existsSync(envExample)) {
  for (const line of fs.readFileSync(envExample, "utf8").split("\n")) {
    const m = line.match(/^\s*#?\s*([A-Z][A-Z0-9_]+)=/);
    if (m) declared.add(m[1]);
  }
}

const missing = new Map();
for (const dir of SCAN_DIRS) {
  for (const file of walk(dir)) {
    const src = fs.readFileSync(file, "utf8");
    for (const m of src.matchAll(/process\.env\.([A-Z][A-Z0-9_]+)/g)) {
      const key = m[1];
      if (BUILTINS.has(key) || declared.has(key)) continue;
      if (!missing.has(key)) missing.set(key, path.relative(ROOT, file));
    }
  }
}

if (missing.size > 0) {
  console.error("[check-env] env vars read by the app but not declared in .env.example:");
  for (const [key, file] of missing) console.error(`  ${key}  (first read: ${file})`);
  console.error("Declare them (with a placeholder or comment) in .env.example.");
  process.exit(1);
}
console.log(`[check-env] OK — all env reads declared in .env.example (${declared.size} declared).`);
