"use client";
// Marketplace listing — APP.F10. Body-only page.
// Layout: collection-marketplace-grid
// TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import * as React from "react";
import { useRouter } from "next/navigation";
import { PageHeader } from "@dbp/ui";
import CatalogGrid from "@dbp/organisms/catalog-grid";

const CATALOG_CONFIG = {
  "entityType": "lab-service",
  "itemLabel": "services",
  "categories": [
    {
      "id": "all",
      "label": "All"
    },
    {
      "id": "imaging",
      "label": "Imaging & Radiology"
    },
    {
      "id": "diagnostic-procedures",
      "label": "Diagnostic Procedures"
    },
    {
      "id": "sample-collection",
      "label": "Sample Collection"
    },
    {
      "id": "back-office",
      "label": "Back Office"
    }
  ],
  "categoryField": "department",
  "cardFields": {
    "title": "name",
    "description": "summary",
    "typeLabel": "department",
    "status": "status",
    "statusTone": "success",
    "footerId": "code"
  },
  "filterFields": [
    {
      "field": "department",
      "label": "Department"
    },
    {
      "field": "status",
      "label": "Status"
    }
  ],
  "detailVariant": "ops"
} as Parameters<typeof CatalogGrid>[0];

export default function MarketplacePage() {
  const router = useRouter();
  return (
    <>
      <PageHeader title="Internal Service Catalog." />
      <CatalogGrid
        {...CATALOG_CONFIG}
        onCardClick={(_entityType, id) => router.push("/marketplace/" + encodeURIComponent(id))}
      />
    </>
  );
}
