// app/(authenticated)/[...slug]/page.tsx — catch-all for nav items without a page yet.
// Body-only — TransactionShell provided by app/(authenticated)/layout.tsx.
// Generated by scaffold-solution — do not edit (run with --force to regenerate).
import Link from "next/link";

export default async function CatchAllPage({
  params,
}: {
  params: Promise<{ slug: string[] }>;
}) {
  const { slug } = await params;
  const path = "/" + slug.join("/");

  return (
    <div className="flex flex-col items-center justify-center text-center px-6" style={{ minHeight: "60vh" }}>
      <p className="font-mono tracking-[0.14em] uppercase text-[var(--color-text-disabled)] mb-4" style={{ fontSize: "11px" }}>
        {path}
      </p>
      <h1 className="text-xl font-semibold mb-2 text-[var(--color-text)]">
        Coming soon
      </h1>
      <p className="text-sm text-[var(--color-text-secondary)] mb-6 max-w-sm">
        This section is being built out. Check back soon or return to the home page.
      </p>
      <Link
        href="/home"
        className="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-md bg-[var(--color-primary)] text-white hover:opacity-90 transition-opacity"
      >
        Return to Home
      </Link>
    </div>
  );
}
