// solution/flags/config.ts — Feature flag defaults for DWS.07.
// Generated by scaffold-solution — do not edit (run with --force to regenerate).
// Import featureFlagDefaults into a Server Component and pass to getFeatureFlags().
// No feature_flags declared in manifest. All useFeatureFlag() calls return false.
export const featureFlagDefaults = {

} as const;

export type FeatureFlagId = keyof typeof featureFlagDefaults;
