"use client";
// Module: DWS.07.S61 — Data Lineage
// Shell: SH.02  Journey stage: 2
// Layout: collection-table
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { CanvasLayout } from "@dbp/shell-transaction/layouts";
import { Button } from "@dbp/ui";
import KpiScorecard from "@dbp/organisms/kpi-scorecard";
import ChartPanel from "@dbp/organisms/chart-panel";

export default function DataLineagePage() {
  return (
      <CanvasLayout>
        <div className="flex justify-end gap-2 mb-4">
          <Button variant="navy" onClick={() => {}}>New record</Button>
        </div>
        <div className="flex flex-col gap-6">
        <KpiScorecard
          key="platform-management-data-lineage-scorecard"
          {...({
        "layout": "grid",
        "kpis": [
                {
                        "id": "platform-management-data-lineage-open",
                        "label": "Open",
                        "entityType": "lab-service",
                        "metric": {
                                "aggregate": "count"
                        },
                        "filters": {
                                "status": "open"
                        },
                        "format": "number",
                        "icon": "Activity"
                },
                {
                        "id": "platform-management-data-lineage-in-progress",
                        "label": "In Progress",
                        "entityType": "lab-service",
                        "metric": {
                                "aggregate": "count"
                        },
                        "filters": {
                                "status": "in-progress"
                        },
                        "format": "number",
                        "icon": "Hash"
                },
                {
                        "id": "platform-management-data-lineage-review",
                        "label": "Review",
                        "entityType": "lab-service",
                        "metric": {
                                "aggregate": "count"
                        },
                        "filters": {
                                "status": "review"
                        },
                        "format": "number",
                        "icon": "Target"
                },
                {
                        "id": "platform-management-data-lineage-done",
                        "label": "Done",
                        "entityType": "lab-service",
                        "metric": {
                                "aggregate": "count"
                        },
                        "filters": {
                                "status": "done"
                        },
                        "format": "number",
                        "icon": "TrendingUp"
                }
        ]
} as Parameters<typeof KpiScorecard>[0])}
        />
        <ChartPanel
          key="platform-management-data-lineage-chart"
          {...({
        "title": "Lab Service by Category",
        "entityType": "lab-service",
        "chartType": "bar",
        "categoryField": "category",
        "series": [
                {
                        "valueField": "id",
                        "label": "Lab Services",
                        "aggregate": "count"
                }
        ],
        "height": 300
} as Parameters<typeof ChartPanel>[0])}
        />
        </div>
      </CanvasLayout>
  );
}
