"use client";
// Authenticated home — APP.F12 rebuild (fixed 4-section composition).
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// WorkspaceHomeHero → WorkspaceHomePlatform → WorkspaceHomeJourney → WorkspaceHomeClosing. No
// greeting card, preview panel, KPI row, activity feed, quick-links deck, or
// search input (design-spec §7 — explicit non-features). No PageHeader.
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { WorkspaceHomeHero, WorkspaceHomePlatform, WorkspaceHomeJourney } from "@dbp/ui";

export default function HomePage() {
  return (
    <div className="min-h-full -m-[var(--shell-gutter)]">
      <WorkspaceHomeHero
        overline={"BIOTEST SERVICING WORKSPACE"}
        headlinePrefix={"Every order, one queue."}
        headlineAccent={"Nothing falls through."}
        
        body={"BioTest Diagnostics Servicing brings intake, capture, and release together across every department — walk-in, self-booked, or referred, staff always know what's next. No internal approval gate: the technician who captures it releases it."}
        primaryAction={{"label":"Open Servicing Queue","href":"/servicing"}}
        secondaryAction={{"label":"Browse Service Catalog","href":"/marketplace/discern"}}
        trustSignals={["Self-certified release, fully audited","Same-day SLA tracked, not assumed","Every department, one queue"]}
        
        
      />
      <WorkspaceHomePlatform
        label={"PLATFORM"}
        heading={""}
        feature={{"index":"00","title":"","description":""}}
        capabilities={[{"kind":"repository","index":"01","title":"Servicing Queue","description":"Every exam-order across every department — imaging, diagnostic procedures, sample collection, back office — captured and self-released, no second reviewer.","chips":[]},{"kind":"collaboration","index":"02","title":"Compliance Ledger","description":"Immutable audit trail on every capture, release, and recapture, exportable on demand for KENAS/KNRA inspection.","chips":[]},{"kind":"analytics","index":"03","title":"Internal Service Catalog","description":"Imaging & Radiology, Diagnostic Procedures, Sample Collection, and Back Office — organised by department, with SLA targets published.","chips":[]}] as { kind: "repository" | "collaboration" | "analytics"; index: string; title: string; description: string; chips: string[] }[]}
        
      />
      <WorkspaceHomeJourney
        label={"HOW IT WORKS"}
        heading={""}
        
        support={""}
        steps={[{"badge":"STEP 01","stage":"01","title":"Order arrives","description":"Walk-in, self-booked via the Patient App, or referred via the Partner Portal — front desk registers it and tags the source.","metricValue":"","metricLabel":""},{"badge":"STEP 02","stage":"02","title":"Technician captures","description":"The assigned technician performs the procedure and judges its own accuracy — no second reviewer in the loop.","metricValue":"","metricLabel":""},{"badge":"STEP 03","stage":"03","title":"Released, same action","description":"The technician releases in the same action that closes the capture. Notification fires automatically.","metricValue":"","metricLabel":""}]}
      />
    </div>
  );
}
