"use client";
// Module: DWS.07.S69 — Security Logs
// Shell: SH.02  Journey stage: 2
// Layout: collection-table
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { CanvasLayout } from "@dbp/shell-transaction/layouts";
import { AdminAuditLog } from "@dbp/ui";

export default function SecurityLogsPage() {
  return (
      <CanvasLayout>
        <AdminAuditLog />
      </CanvasLayout>
  );
}
