"use client";
// Authenticated client shell — mounts TransactionShell ONCE for the route group.
// Generated by scaffold-solution — do not edit (run with --force to regenerate).
//
// SECURITY NOTE: server-side auth enforcement lives in layout.tsx (the server
// gate reading the middleware-verified x-dbp-session header). The useAuth()
// guard below is UX-only — it catches session expiry during client navigation
// and avoids a flash of stale chrome; it is NOT the security boundary.
//
// The SOLUTION_NAV constant is built once here; pages in this group are
// body-only (no per-page shell wrapper needed).
import * as React from "react";
import type { ReactNode } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useAuth } from "@dbp/ps-auth/client";
import TransactionShell from "@dbp/shell-transaction";
import { SolutionChrome, SolutionSidebarSwitcher } from "../solution-chrome";
import { SolutionFooter } from "../solution-footer";
import { BreadcrumbProvider } from "@dbp/ui";

const SOLUTION_NAV = {
  topBar: <SolutionChrome />,
  footer: <SolutionFooter />,
  // N30 ruling (supersedes N27's static identity block): the sidebar identity
  // block IS the workspace/tenant switcher — active tenant on the primary line,
  // solution name as the subtitle, popover with memberships + sign out.
  identitySlot: (collapsed: boolean) => <SolutionSidebarSwitcher collapsed={collapsed} />,
  sections: [
  {
    "id": "orientation",
    "label": "ORIENTATION",
    "items": [
      {
        "id": "getting-started",
        "label": "Getting Started",
        "icon": "BookOpen",
        "children": [
          {
            "id": "welcome-home",
            "label": "Welcome / Home",
            "href": "/home"
          },
          {
            "id": "onboarding",
            "label": "Onboarding",
            "href": "/onboarding"
          }
        ]
      },
      {
        "id": "quick-links",
        "label": "Quick Links",
        "icon": "Zap",
        "children": [
          {
            "id": "my-dashboard",
            "label": "My Dashboard",
            "href": "/dashboard"
          },
          {
            "id": "my-work",
            "label": "My Work",
            "href": "/my-work"
          },
          {
            "id": "ai-cockpit",
            "label": "AI Cockpit",
            "href": "/copilot"
          }
        ]
      }
    ]
  },
  {
    "id": "marketplace",
    "label": "MARKETPLACE",
    "items": [
      {
        "id": "catalogue",
        "label": "Catalogue",
        "icon": "LayoutGrid",
        "children": [
          {
            "id": "discern",
            "label": "Discern",
            "href": "/marketplace/discern"
          },
          {
            "id": "design",
            "label": "Design",
            "href": "/marketplace/design"
          },
          {
            "id": "deploy",
            "label": "Deploy",
            "href": "/marketplace/deploy"
          },
          {
            "id": "drive",
            "label": "Drive",
            "href": "/marketplace/drive"
          }
        ]
      },
      {
        "id": "transactions",
        "label": "Transactions",
        "icon": "ArrowLeftRight",
        "children": [
          {
            "id": "enquiries",
            "label": "Enquiries",
            "href": "/transactions/enquiries"
          },
          {
            "id": "requests",
            "label": "Requests",
            "href": "/transactions/requests"
          },
          {
            "id": "support-tickets",
            "label": "Support Tickets",
            "href": "/transactions/support-tickets"
          },
          {
            "id": "wallet",
            "label": "Wallet",
            "href": "/transactions/wallet"
          }
        ]
      },
      {
        "id": "collaboration",
        "label": "Collaboration",
        "icon": "Users",
        "children": [
          {
            "id": "chat",
            "label": "Chat",
            "href": "/collaboration/chat"
          },
          {
            "id": "calendar",
            "label": "Calendar",
            "href": "/collaboration/calendar"
          },
          {
            "id": "forums",
            "label": "Forums",
            "href": "/collaboration/forums"
          }
        ]
      }
    ]
  },
  {
    "id": "workspace",
    "label": "WORKSPACE",
    "items": [
      {
        "id": "manage-work",
        "label": "Manage Work",
        "icon": "ListChecks",
        "children": [
          {
            "id": "tasks",
            "label": "Tasks",
            "href": "/manage-work/tasks"
          },
          {
            "id": "cases",
            "label": "Cases",
            "href": "/manage-work/cases"
          },
          {
            "id": "assignments",
            "label": "Assignments",
            "href": "/manage-work/assignments"
          },
          {
            "id": "approvals",
            "label": "Approvals",
            "href": "/manage-work/approvals"
          },
          {
            "id": "reviews",
            "label": "Reviews",
            "href": "/manage-work/reviews"
          },
          {
            "id": "escalations",
            "label": "Escalations",
            "href": "/manage-work/escalations"
          }
        ]
      },
      {
        "id": "monitor-work",
        "label": "Monitor Work",
        "icon": "Activity",
        "children": [
          {
            "id": "work-queue",
            "label": "Work Queue",
            "href": "/monitor-work/queue"
          },
          {
            "id": "sla-tracking",
            "label": "SLA Tracking",
            "href": "/monitor-work/sla"
          },
          {
            "id": "mw-alerts",
            "label": "Alerts",
            "href": "/monitor-work/alerts"
          }
        ]
      }
    ]
  },
  {
    "id": "service-operations",
    "label": "SERVICE OPERATIONS",
    "items": [
      {
        "id": "manage-services",
        "label": "Manage Services",
        "icon": "Settings2",
        "children": [
          {
            "id": "service-catalogue",
            "label": "Service Catalogue",
            "href": "/manage-services/catalogue"
          },
          {
            "id": "service-requests",
            "label": "Service Requests",
            "href": "/manage-services/requests"
          },
          {
            "id": "service-lifecycle",
            "label": "Service Lifecycle",
            "href": "/manage-services/lifecycle"
          },
          {
            "id": "service-quality",
            "label": "Service Quality",
            "href": "/manage-services/quality"
          }
        ]
      },
      {
        "id": "manage-relationships",
        "label": "Manage Relationships",
        "icon": "Handshake",
        "children": [
          {
            "id": "customers",
            "label": "Customers / Participants",
            "href": "/manage-relationships/customers"
          },
          {
            "id": "partners",
            "label": "Partners",
            "href": "/manage-relationships/partners"
          },
          {
            "id": "providers",
            "label": "Providers",
            "href": "/manage-relationships/providers"
          },
          {
            "id": "account-management",
            "label": "Account Management",
            "href": "/manage-relationships/accounts"
          }
        ]
      },
      {
        "id": "manage-delivery",
        "label": "Manage Delivery",
        "icon": "PackageCheck",
        "children": [
          {
            "id": "delivery-plans",
            "label": "Delivery Plans",
            "href": "/manage-delivery/plans"
          },
          {
            "id": "delivery-tasks",
            "label": "Tasks",
            "href": "/manage-delivery/tasks"
          },
          {
            "id": "delivery-cases",
            "label": "Cases",
            "href": "/manage-delivery/cases"
          },
          {
            "id": "incidents",
            "label": "Incidents",
            "href": "/manage-delivery/incidents"
          },
          {
            "id": "delivery-escalations",
            "label": "Escalations",
            "href": "/manage-delivery/escalations"
          },
          {
            "id": "fulfilment-tracking",
            "label": "Fulfilment Tracking",
            "href": "/manage-delivery/fulfilment"
          }
        ]
      }
    ]
  },
  {
    "id": "operational-intelligence",
    "label": "OPERATIONAL INTELLIGENCE",
    "items": [
      {
        "id": "dashboards",
        "label": "Dashboards",
        "icon": "LayoutDashboard",
        "children": [
          {
            "id": "operational-dashboards",
            "label": "Operational Dashboards",
            "href": "/dashboards/operational"
          },
          {
            "id": "executive-dashboards",
            "label": "Executive Dashboards",
            "href": "/dashboards/executive"
          },
          {
            "id": "custom-dashboards",
            "label": "Custom Dashboards",
            "href": "/dashboards/custom"
          },
          {
            "id": "alerts-notifications",
            "label": "Alerts & Notifications",
            "href": "/dashboards/alerts"
          },
          {
            "id": "kpi-scorecards",
            "label": "KPI Scorecards",
            "href": "/dashboards/scorecards"
          }
        ]
      },
      {
        "id": "analytics",
        "label": "Analytics",
        "icon": "TrendingUp",
        "children": [
          {
            "id": "adhoc-analysis",
            "label": "Ad-hoc Analysis",
            "href": "/analytics/adhoc"
          },
          {
            "id": "trend-analysis",
            "label": "Trend Analysis",
            "href": "/analytics/trends"
          },
          {
            "id": "root-cause",
            "label": "Root Cause Analysis",
            "href": "/analytics/root-cause"
          },
          {
            "id": "cohort-analysis",
            "label": "Cohort Analysis",
            "href": "/analytics/cohort"
          },
          {
            "id": "benchmarking",
            "label": "Benchmarking",
            "href": "/analytics/benchmarking"
          }
        ]
      },
      {
        "id": "reports",
        "label": "Reports",
        "icon": "FileBarChart",
        "children": [
          {
            "id": "standard-reports",
            "label": "Standard Reports",
            "href": "/reports/standard"
          },
          {
            "id": "custom-reports",
            "label": "Custom Reports",
            "href": "/reports/custom"
          },
          {
            "id": "scheduled-reports",
            "label": "Scheduled Reports",
            "href": "/reports/scheduled"
          },
          {
            "id": "report-subscriptions",
            "label": "Report Subscriptions",
            "href": "/reports/subscriptions"
          },
          {
            "id": "export-sharing",
            "label": "Export & Sharing",
            "href": "/reports/export"
          }
        ]
      },
      {
        "id": "ai-agents",
        "label": "AI Agents",
        "icon": "Bot",
        "children": [
          {
            "id": "insight-agent",
            "label": "Insight Agent",
            "href": "/ai-agents/insight"
          },
          {
            "id": "anomaly-agent",
            "label": "Anomaly Detection Agent",
            "href": "/ai-agents/anomaly"
          },
          {
            "id": "recommendation-agent",
            "label": "Recommendation Agent",
            "href": "/ai-agents/recommendation"
          },
          {
            "id": "automation-agent",
            "label": "Automation Agent",
            "href": "/ai-agents/automation"
          },
          {
            "id": "custom-ai-agents",
            "label": "Custom AI Agents",
            "href": "/ai-agents/custom"
          }
        ]
      }
    ]
  },
  {
    "id": "platform-management",
    "label": "PLATFORM MANAGEMENT",
    "items": [
      {
        "id": "general",
        "label": "General",
        "icon": "SlidersHorizontal",
        "children": [
          {
            "id": "org-setup",
            "label": "Organisation Setup",
            "href": "/admin/organisation"
          },
          {
            "id": "workspace-settings",
            "label": "Workspace Settings",
            "href": "/admin/workspace-settings"
          },
          {
            "id": "branding",
            "label": "Branding",
            "href": "/admin/branding"
          },
          {
            "id": "regional-language",
            "label": "Regional & Language",
            "href": "/admin/regional"
          },
          {
            "id": "business-hours",
            "label": "Business Hours",
            "href": "/admin/business-hours"
          },
          {
            "id": "default-values",
            "label": "Default Values",
            "href": "/admin/defaults"
          }
        ]
      },
      {
        "id": "users-access",
        "label": "Users & Access",
        "icon": "Users",
        "children": [
          {
            "id": "user-management",
            "label": "User Management",
            "href": "/admin/users"
          },
          {
            "id": "role-management",
            "label": "Role Management",
            "href": "/admin/roles"
          },
          {
            "id": "access-control",
            "label": "Access Control",
            "href": "/admin/access-control"
          },
          {
            "id": "auth-settings",
            "label": "Authentication Settings",
            "href": "/admin/auth"
          }
        ]
      },
      {
        "id": "processes-automation",
        "label": "Processes & Automation",
        "icon": "Workflow",
        "children": [
          {
            "id": "form-builder",
            "label": "Form Builder",
            "href": "/admin/form-builder"
          },
          {
            "id": "workflow-builder",
            "label": "Workflow Builder",
            "href": "/admin/workflow-builder"
          },
          {
            "id": "rule-management",
            "label": "Rule Management",
            "href": "/admin/rules"
          }
        ]
      },
      {
        "id": "data-structure",
        "label": "Data & Structure",
        "icon": "Database",
        "children": [
          {
            "id": "data-model",
            "label": "Data Model",
            "href": "/admin/data-model"
          },
          {
            "id": "master-data",
            "label": "Master Data",
            "href": "/admin/master-data"
          },
          {
            "id": "reference-data",
            "label": "Reference Data",
            "href": "/admin/reference-data"
          },
          {
            "id": "data-quality",
            "label": "Data Quality Rules",
            "href": "/admin/data-quality"
          },
          {
            "id": "data-lineage",
            "label": "Data Lineage",
            "href": "/admin/data-lineage"
          }
        ]
      },
      {
        "id": "integrations",
        "label": "Integrations",
        "icon": "Plug",
        "children": [
          {
            "id": "api-management",
            "label": "API Management",
            "href": "/admin/apis"
          },
          {
            "id": "connectors",
            "label": "Connectors",
            "href": "/admin/connectors"
          },
          {
            "id": "data-flows",
            "label": "Data Flows",
            "href": "/admin/data-flows"
          },
          {
            "id": "data-import",
            "label": "Data Import",
            "href": "/admin/data-import"
          }
        ]
      },
      {
        "id": "platform",
        "label": "Platform",
        "icon": "Server",
        "children": [
          {
            "id": "policy-management",
            "label": "Policy Management",
            "href": "/admin/policies"
          },
          {
            "id": "control-register",
            "label": "Control Register",
            "href": "/admin/controls"
          },
          {
            "id": "risk-register",
            "label": "Risk Register",
            "href": "/admin/risks"
          },
          {
            "id": "security-logs",
            "label": "Security Logs",
            "href": "/admin/security-logs"
          }
        ]
      }
    ]
  }
],
};

export default function AuthenticatedClientShell({ children }: { children: ReactNode }) {
  const router = useRouter();
  const { user, status } = useAuth();

  React.useEffect(() => {
    if (status !== "loading" && !user) {
      // Session gone client-side (expiry mid-navigation) — bounce to login, preserving destination.
      const redirect = encodeURIComponent(window.location.pathname + window.location.search);
      router.replace(`/login?redirect=${redirect}`);
    }
  }, [user, status, router]);

  // While loading or redirecting, render nothing to avoid a flash of shell chrome.
  if (status === "loading" || !user) return null;

  // N36: BreadcrumbProvider wraps both the top bar (SolutionChrome, mounted
  // via nav.topBar) and the page body — pages call useBreadcrumbOverride() to
  // replace the top-bar breadcrumb's terminal crumb with the loaded record's
  // display name once it resolves.
  return (
    <BreadcrumbProvider>
      <TransactionShell
        nav={SOLUTION_NAV}
        slots={{
          main: (
            <>
              {children}
            </>
          ),
        }}
        // ADR-0040: shell-rendered anchors (collapsed nav strip, help link) get
        // client-side routing instead of full page reloads.
        linkComponent={Link}
      />
    </BreadcrumbProvider>
  );
}
