// Authenticated route-group layout — SERVER-SIDE auth gate (ADR-0027 + DWS.01 audit 2.3).
// Generated by scaffold-solution — do not edit (run with --force to regenerate).
//
// Enforcement happens HERE, on the server, before any authenticated markup is
// rendered: middleware.ts verifies the session against PS.AUTH and forwards it
// as x-dbp-session (plus the request path as x-dbp-pathname). No header = not
// authenticated = redirect to /login. The client shell's useAuth() redirect is
// UX-only (session expiry during navigation), never the security boundary.
import type { ReactNode } from "react";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import AuthenticatedClientShell from "./authenticated-client-shell";

export default async function AuthenticatedLayout({ children }: { children: ReactNode }) {
  const h = await headers();
  if (!h.get("x-dbp-session")) {
    const intended = h.get("x-dbp-pathname") ?? "";
    redirect(intended ? `/login?redirect=${encodeURIComponent(intended)}` : "/login");
  }
  return <AuthenticatedClientShell>{children}</AuthenticatedClientShell>;
}
