"use client";
// Module: DWS.07.S01 — My Dashboard
// Shell: SH.02  Journey stage: 2
// Layout: overview-grid
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { OverviewGridLayout } from "@dbp/shell-transaction/layouts";
import WorkspaceDashboard from "@dbp/organisms/workspace-dashboard";
import { WorkspaceDashboardActions } from "@dbp/organisms/workspace-dashboard";

export default function MyDashboardPage() {
  return (
      <OverviewGridLayout>
        <div className="flex justify-end gap-2 mb-4">
          <WorkspaceDashboardActions actions={[
        {
                "label": "Ask AI",
                "primary": true,
                "href": "/copilot"
        }
]} />
        </div>
        <WorkspaceDashboard
          key="orientation-my-dashboard"
          {...({
        "actions": [
                {
                        "label": "Ask AI",
                        "primary": true,
                        "href": "/copilot"
                }
        ],
        "tasksEntityType": "demo-record",
        "taskGroups": [
                {
                        "key": "in-progress",
                        "label": "In Progress",
                        "statuses": [
                                "in-progress"
                        ]
                },
                {
                        "key": "to-do",
                        "label": "To Do",
                        "statuses": [
                                "open"
                        ]
                },
                {
                        "key": "upcoming",
                        "label": "Upcoming",
                        "statuses": [
                                "review"
                        ]
                }
        ],
        "taskFields": {
                "name": "name",
                "priority": "priority",
                "dueDate": "updated",
                "status": "status"
        },
        "goals": [
                {
                        "label": "Check emails and messages",
                        "context": "Product launch · My Projects",
                        "value": 73
                },
                {
                        "label": "Prepare a brief status update to the client",
                        "context": "Product launch · My Projects",
                        "value": 11
                },
                {
                        "label": "Update project documentation",
                        "context": "Team brainstorm · My Projects",
                        "value": 63
                }
        ],
        "projects": [
                {
                        "name": "Product launch",
                        "tasks": 6,
                        "teammates": 12,
                        "icon": "P",
                        "tone": "primary"
                },
                {
                        "name": "Team brainstorm",
                        "tasks": 2,
                        "teammates": 32,
                        "icon": "T",
                        "tone": "info"
                },
                {
                        "name": "Branding launch",
                        "tasks": 4,
                        "teammates": 9,
                        "icon": "B",
                        "tone": "success"
                }
        ],
        "calendar": {
                "month": "July",
                "days": [
                        {
                                "dow": "Fri",
                                "day": 4
                        },
                        {
                                "dow": "Sat",
                                "day": 5
                        },
                        {
                                "dow": "Sun",
                                "day": 6
                        },
                        {
                                "dow": "Mon",
                                "day": 7,
                                "active": true
                        },
                        {
                                "dow": "Tue",
                                "day": 8
                        },
                        {
                                "dow": "Wed",
                                "day": 9
                        },
                        {
                                "dow": "Thu",
                                "day": 10
                        }
                ],
                "events": [
                        {
                                "title": "Meeting with VP",
                                "time": "Today · 10:00 – 11:00 am",
                                "provider": "Google Meet",
                                "attendees": 5
                        }
                ]
        },
        "remindersEntityType": "reminder"
} as Parameters<typeof WorkspaceDashboard>[0])}
        />
      </OverviewGridLayout>
  );
}
