// Generated by scaffold-solution — do not edit.
// N5 a11y smoke gate (warn-baseline). Scans this solution's own key pages with
// @axe-core/playwright and fails only if violations exceed the committed baseline
// (infra/05-policy/a11y-baseline.json). Mirrors the monorepo's e2e/a11y.spec.ts, scoped to
// this app's own root instead of apps/dws-01.
import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import baseline from "../infra/05-policy/a11y-baseline.json" with { type: "json" };

const ROUTES: Array<{ key: keyof typeof baseline; path: string }> = [
  { key: "/login", path: "/login" },
];

for (const { key, path } of ROUTES) {
  test(`a11y smoke — ${key}`, async ({ page }) => {
    await page.goto(path);
    const results = await new AxeBuilder({ page }).analyze();

    const expected = baseline[key];
    expect(
      expected,
      `No a11y-baseline.json entry for "${key}" — add one before scanning a new route.`,
    ).toBeDefined();

    test.info().annotations.push({
      type: "note",
      description: `${key}: ${results.violations.length} violation(s) — ${results.violations
        .map((v) => v.id)
        .join(", ") || "none"}`,
    });

    // Warn-baseline: fail only if violations exceed the committed baseline count.
    expect(
      results.violations.length,
      `a11y violations for ${key} increased beyond baseline (${expected.violationCount}): ${JSON.stringify(
        results.violations.map((v) => ({ id: v.id, impact: v.impact })),
      )}`,
    ).toBeLessThanOrEqual(expected.violationCount);
  });
}
