// Generated by scaffold-solution — do not edit.
// Deterministic companion to e2e/ux-audit-brief.md's agentic audit. Proves the
// authenticated shell is real, not a demo shell: login succeeds, every synthesized
// nav route loads without a console error, main content is not a placeholder, list
// pages return seeded data, and each page exposes at least one enabled primary
// action. Routes come from the SAME nav model the generator synthesizes elsewhere
// in scaffold-solution.mjs (protectedPrefixes/manifest.modules) — never hand-listed.
import { test, expect, type Page } from "@playwright/test";

const DEMO_ACCOUNT = { email: "platform-admin@alpha.dev.local", password: "dbp-dev-password" };

const ROUTES: Array<{ path: string; label: string }> = [
    {
      path: "/admin/access-control",
      label: "Access Control"
    },
    {
      path: "/admin/apis",
      label: "API Management"
    },
    {
      path: "/admin/auth",
      label: "Authentication Settings"
    },
    {
      path: "/admin/branding",
      label: "Branding"
    },
    {
      path: "/admin/business-hours",
      label: "Business Hours"
    },
    {
      path: "/admin/connectors",
      label: "Connectors"
    },
    {
      path: "/admin/controls",
      label: "Control Register"
    },
    {
      path: "/admin/data-flows",
      label: "Data Flows"
    },
    {
      path: "/admin/data-import",
      label: "Data Import"
    },
    {
      path: "/admin/data-lineage",
      label: "Data Lineage"
    },
    {
      path: "/admin/data-model",
      label: "Data Model"
    },
    {
      path: "/admin/data-quality",
      label: "Data Quality Rules"
    },
    {
      path: "/admin/defaults",
      label: "Default Values"
    },
    {
      path: "/admin/form-builder",
      label: "Form Builder"
    },
    {
      path: "/admin/master-data",
      label: "Master Data"
    },
    {
      path: "/admin/organisation",
      label: "Organisation Setup"
    },
    {
      path: "/admin/policies",
      label: "Policy Management"
    },
    {
      path: "/admin/reference-data",
      label: "Reference Data"
    },
    {
      path: "/admin/regional",
      label: "Regional & Language"
    },
    {
      path: "/admin/risks",
      label: "Risk Register"
    },
    {
      path: "/admin/roles",
      label: "Role Management"
    },
    {
      path: "/admin/rules",
      label: "Rule Management"
    },
    {
      path: "/admin/security-logs",
      label: "Security Logs"
    },
    {
      path: "/admin/users",
      label: "User Management"
    },
    {
      path: "/admin/workflow-builder",
      label: "Workflow Builder"
    },
    {
      path: "/admin/workspace-settings",
      label: "Workspace Settings"
    },
    {
      path: "/analytics/adhoc",
      label: "Ad-hoc Analysis"
    },
    {
      path: "/analytics/benchmarking",
      label: "Benchmarking"
    },
    {
      path: "/analytics/cohort",
      label: "Cohort Analysis"
    },
    {
      path: "/analytics/root-cause",
      label: "Root Cause Analysis"
    },
    {
      path: "/analytics/trends",
      label: "Trend Analysis"
    },
    {
      path: "/collaboration/calendar",
      label: "Calendar"
    },
    {
      path: "/collaboration/forums",
      label: "Forums"
    },
    {
      path: "/dashboard",
      label: "My Dashboard"
    },
    {
      path: "/dashboards/alerts",
      label: "Alerts & Notifications"
    },
    {
      path: "/dashboards/custom",
      label: "Custom Dashboards"
    },
    {
      path: "/dashboards/executive",
      label: "Executive Dashboards"
    },
    {
      path: "/dashboards/operational",
      label: "Operational Dashboards"
    },
    {
      path: "/dashboards/scorecards",
      label: "KPI Scorecards"
    },
    {
      path: "/home",
      label: "Home"
    },
    {
      path: "/manage-delivery/cases",
      label: "Cases"
    },
    {
      path: "/manage-delivery/escalations",
      label: "Escalations"
    },
    {
      path: "/manage-delivery/fulfilment",
      label: "Fulfilment Tracking"
    },
    {
      path: "/manage-delivery/incidents",
      label: "Incidents"
    },
    {
      path: "/manage-delivery/plans",
      label: "Delivery Plans"
    },
    {
      path: "/manage-delivery/tasks",
      label: "Tasks"
    },
    {
      path: "/manage-relationships/accounts",
      label: "Account Management"
    },
    {
      path: "/manage-relationships/customers",
      label: "Customers / Participants"
    },
    {
      path: "/manage-relationships/partners",
      label: "Partners"
    },
    {
      path: "/manage-relationships/providers",
      label: "Providers"
    },
    {
      path: "/manage-services/catalogue",
      label: "Service Catalogue"
    },
    {
      path: "/manage-services/lifecycle",
      label: "Service Lifecycle"
    },
    {
      path: "/manage-services/quality",
      label: "Service Quality"
    },
    {
      path: "/manage-services/requests",
      label: "Service Requests"
    },
    {
      path: "/manage-work/assignments",
      label: "Assignments"
    },
    {
      path: "/manage-work/cases",
      label: "Cases"
    },
    {
      path: "/manage-work/escalations",
      label: "Escalations"
    },
    {
      path: "/manage-work/reviews",
      label: "Reviews"
    },
    {
      path: "/marketplace",
      label: "Marketplace"
    },
    {
      path: "/marketplace/deploy",
      label: "Sample Collection"
    },
    {
      path: "/marketplace/design",
      label: "Diagnostic Procedures"
    },
    {
      path: "/marketplace/discern",
      label: "Imaging & Radiology"
    },
    {
      path: "/marketplace/drive",
      label: "Back Office"
    },
    {
      path: "/monitor-work/alerts",
      label: "Alerts"
    },
    {
      path: "/monitor-work/queue",
      label: "Work Queue"
    },
    {
      path: "/my-work",
      label: "My Work"
    },
    {
      path: "/reports/custom",
      label: "Custom Reports"
    },
    {
      path: "/reports/export",
      label: "Export & Sharing"
    },
    {
      path: "/reports/scheduled",
      label: "Scheduled Reports"
    },
    {
      path: "/reports/standard",
      label: "Standard Reports"
    },
    {
      path: "/reports/subscriptions",
      label: "Report Subscriptions"
    },
    {
      path: "/servicing",
      label: "Servicing Queue"
    },
    {
      path: "/transactions/enquiries",
      label: "Enquiries"
    },
    {
      path: "/transactions/requests",
      label: "Requests"
    },
    {
      path: "/transactions/support-tickets",
      label: "Support Tickets"
    },
    {
      path: "/transactions/wallet",
      label: "Wallet"
    }
  ];

const PLACEHOLDER_PATTERNS = [/\bTODO\b/i, /\bplaceholder\b/i, /\blorem ipsum\b/i];
const MIN_CONTENT_LENGTH = 40;

async function login(page: Page) {
  await page.goto("/login");
  await page.getByLabel(/email/i).fill(DEMO_ACCOUNT.email);
  await page.getByLabel(/password/i).fill(DEMO_ACCOUNT.password);
  await page.getByRole("button", { name: /sign in|log in/i }).click();
  // Login must land somewhere other than /login within a bounded timeout — a
  // broken login is a critical finding for the agentic brief and a hard test
  // failure here.
  await page.waitForURL((url) => !url.pathname.startsWith("/login"), { timeout: 10_000 });
}

test.describe("UX shell audit", () => {
  test("demo login succeeds", async ({ page }) => {
    await login(page);
    await expect(page).not.toHaveURL(/\/login$/);
  });

  for (const route of ROUTES) {
    test(`${route.label} (${route.path}) — loads with real, non-placeholder content`, async ({ page }) => {
      const consoleErrors: string[] = [];
      page.on("console", (msg) => {
        if (msg.type() === "error") consoleErrors.push(msg.text());
      });

      await login(page);
      await page.goto(route.path);

      // A perpetual spinner/skeleton is a defect: give it a few seconds to resolve,
      // then assert it's gone.
      const spinner = page.locator("[role='status'], [data-loading='true'], .animate-spin");
      if (await spinner.count() > 0) {
        await expect(spinner.first()).toBeHidden({ timeout: 5_000 });
      }

      // Poll rather than one-shot: client-rendered list pages can pass "load"
      // before their data fetch resolves, briefly rendering only the chrome.
      const readText = async () =>
        (await page.locator("main").innerText().catch(() => page.locator("body").innerText())) ?? "";
      await expect
        .poll(async () => (await readText()).trim().length, {
          message: `${route.path} rendered suspiciously little content`,
          timeout: 15_000,
        })
        .toBeGreaterThan(MIN_CONTENT_LENGTH);
      const bodyText = await readText();
      for (const pattern of PLACEHOLDER_PATTERNS) {
        expect(bodyText, `${route.path} contains literal placeholder text (${pattern})`).not.toMatch(pattern);
      }

      expect(consoleErrors, `${route.path} logged uncaught console errors: ${consoleErrors.join("; ")}`).toHaveLength(0);

      // At least one primary action (enabled button) should exist on an
      // authenticated workspace page — a page with zero enabled controls is a
      // dead end for a real user.
      const enabledButtons = page.locator("button:not([disabled]), a[href]:not([aria-disabled='true'])");
      expect(
        await enabledButtons.count(),
        `${route.path} exposes no enabled primary action`,
      ).toBeGreaterThan(0);
    });
  }

  test("at least one list page shows seeded data rows", async ({ page }) => {
    await login(page);
    let sawRows = false;
    for (const route of ROUTES) {
      await page.goto(route.path);
      const rows = page.locator("table tbody tr, [role='row'], [data-testid='list-row']");
      if ((await rows.count()) > 0) {
        sawRows = true;
        break;
      }
    }
    expect(sawRows, "No route showed any list/table rows — seeded data may be missing").toBe(true);
  });
});
