"use client";
// Module: DWS.07.S42 — Report Subscriptions
// Shell: SH.02  Journey stage: 2
// Layout: config-form-custom
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { SettingsLayout } from "@dbp/shell-transaction/layouts";
import { SettingsNav } from "@dbp/ui";
import EntityList from "@dbp/organisms/entity-list";

export default function ReportSubscriptionsPage() {
  return (
      <SettingsLayout
        nav={<SettingsNav links={[{"href":"/admin/organisation","label":"Organisation Setup"},{"href":"/admin/workspace-settings","label":"Workspace Settings"},{"href":"/admin/branding","label":"Branding"},{"href":"/admin/regional","label":"Regional & Language"},{"href":"/admin/business-hours","label":"Business Hours"},{"href":"/admin/defaults","label":"Default Values"},{"href":"/admin/users","label":"User Management"},{"href":"/admin/roles","label":"Role Management"},{"href":"/admin/access-control","label":"Access Control"},{"href":"/admin/auth","label":"Authentication Settings"},{"href":"/admin/form-builder","label":"Form Builder"},{"href":"/admin/workflow-builder","label":"Workflow Builder"},{"href":"/admin/rules","label":"Rule Management"},{"href":"/admin/data-model","label":"Data Model"},{"href":"/admin/master-data","label":"Master Data"},{"href":"/admin/reference-data","label":"Reference Data"},{"href":"/admin/data-quality","label":"Data Quality Rules"},{"href":"/admin/data-lineage","label":"Data Lineage"},{"href":"/admin/apis","label":"API Management"},{"href":"/admin/connectors","label":"Connectors"},{"href":"/admin/data-flows","label":"Data Flows"},{"href":"/admin/data-import","label":"Data Import"},{"href":"/admin/policies","label":"Policy Management"},{"href":"/admin/controls","label":"Control Register"},{"href":"/admin/risks","label":"Risk Register"},{"href":"/admin/security-logs","label":"Security Logs"}]} />}
      >
        <EntityList
          key="operational-intelligence-report-subscriptions"
          {...({
        "entityType": "lab-service",
        "columns": [
                {
                        "field": "name",
                        "label": "Name",
                        "sortable": true,
                        "editable": true,
                        "editType": "text"
                },
                {
                        "field": "summary",
                        "label": "Summary",
                        "sortable": true,
                        "editable": true,
                        "editType": "text"
                },
                {
                        "field": "department",
                        "label": "Department",
                        "sortable": true,
                        "editable": true,
                        "editType": "select",
                        "editOptions": [
                                {
                                        "value": "imaging",
                                        "label": "Imaging"
                                },
                                {
                                        "value": "diagnostic-procedures",
                                        "label": "Diagnostic Procedures"
                                },
                                {
                                        "value": "sample-collection",
                                        "label": "Sample Collection"
                                },
                                {
                                        "value": "back-office",
                                        "label": "Back Office"
                                }
                        ]
                },
                {
                        "field": "status",
                        "label": "Status",
                        "sortable": true,
                        "editable": true,
                        "editType": "select",
                        "editOptions": [
                                {
                                        "value": "active",
                                        "label": "Active"
                                },
                                {
                                        "value": "draft",
                                        "label": "Draft"
                                }
                        ]
                },
                {
                        "field": "code",
                        "label": "Code",
                        "sortable": true,
                        "editable": true,
                        "editType": "text"
                },
                {
                        "field": "slaTargetHours",
                        "label": "SlaTargetHours",
                        "sortable": true,
                        "editable": true,
                        "editType": "number"
                }
        ],
        "pageSize": 15,
        "enableSearch": true,
        "listTabs": [
                {
                        "key": "all",
                        "label": "All",
                        "where": []
                },
                {
                        "key": "active",
                        "label": "Active",
                        "where": [
                                {
                                        "field": "status",
                                        "op": "is",
                                        "value": "active"
                                }
                        ]
                },
                {
                        "key": "draft",
                        "label": "Draft",
                        "where": [
                                {
                                        "field": "status",
                                        "op": "is",
                                        "value": "draft"
                                }
                        ]
                }
        ],
        "detailDrawer": {
                "titleField": "name",
                "subtitleFields": [
                        "code"
                ],
                "entityLabel": "Lab Service",
                "statusField": "status",
                "statusTones": {
                        "active": "success",
                        "draft": "info"
                },
                "codeField": "code",
                "descriptionField": "summary",
                "quickActions": [
                        {
                                "id": "mark-active",
                                "label": "Mark active",
                                "patch": {
                                        "status": "active"
                                }
                        }
                ],
                "headerMenu": [
                        {
                                "id": "mark-draft",
                                "label": "Mark draft",
                                "patch": {
                                        "status": "draft"
                                }
                        }
                ],
                "variants": {},
                "labels": {},
                "defaultSections": [
                        {
                                "id": "overview",
                                "title": "Overview",
                                "fields": [
                                        {
                                                "id": "name",
                                                "label": "Name",
                                                "format": "text",
                                                "editable": false
                                        },
                                        {
                                                "id": "summary",
                                                "label": "Summary",
                                                "format": "text",
                                                "editable": false
                                        },
                                        {
                                                "id": "department",
                                                "label": "Department",
                                                "format": "badge",
                                                "editable": false
                                        },
                                        {
                                                "id": "status",
                                                "label": "Status",
                                                "format": "text",
                                                "render": "status-dot",
                                                "badgeTones": {
                                                        "active": "success",
                                                        "draft": "info"
                                                },
                                                "editable": false
                                        },
                                        {
                                                "id": "code",
                                                "label": "Code",
                                                "format": "text",
                                                "editable": false
                                        },
                                        {
                                                "id": "slaTargetHours",
                                                "label": "SlaTargetHours",
                                                "format": "text",
                                                "editable": false
                                        }
                                ]
                        }
                ],
                "tabs": [
                        {
                                "id": "overview",
                                "label": "Overview",
                                "kind": "fields"
                        },
                        {
                                "id": "comments",
                                "label": "Comments",
                                "kind": "comments"
                        },
                        {
                                "id": "audit",
                                "label": "Audit",
                                "kind": "audit"
                        }
                ],
                "comments": {
                        "entityType": "lab-service"
                },
                "deepLink": true,
                "expandable": true
        }
} as Parameters<typeof EntityList>[0])}
        />
      </SettingsLayout>
  );
}
