"use client";
// Module: DWS.07.S51 — Role Management
// Shell: SH.02  Journey stage: 2
// Layout: collection-table
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { CanvasLayout } from "@dbp/shell-transaction/layouts";
import { AdminRoleList } from "@dbp/organisms/admin-role-list";

export default function RoleManagementPage() {
  return (
      <CanvasLayout>
        <AdminRoleList />
      </CanvasLayout>
  );
}
