"use client";
// app/global-error.tsx — root-level error boundary (must include own html/body).
// Generated by scaffold-solution — do not edit (run with --force to regenerate).
import { useEffect } from "react";

export default function GlobalError({ error, reset }: { error: Error & { digest?: string }; reset: () => void }) {
  useEffect(() => { console.error("[DWS.07] global-error:", error); }, [error]);
  return (
    <html lang="en">
      {/* eslint-disable-next-line dbp-local-hex/no-raw-design-values -- root-layout crash boundary: layout.tsx (which loads the token CSS) may itself have failed to render, so this cannot depend on --color-* custom properties being defined. */}
      <body style={{ fontFamily: "system-ui, sans-serif", display: "flex", alignItems: "center", justifyContent: "center", minHeight: "100vh", margin: 0, backgroundColor: "#f8f9fa", color: "#1a1a2e" }}>
        <div style={{ textAlign: "center", maxWidth: 480, padding: "2rem" }}>
          {/* eslint-disable-next-line dbp-local-hex/no-raw-design-values -- see body tag above: token CSS may not be loaded in this boundary. */}
          <p style={{ fontSize: "11px", letterSpacing: "0.14em", textTransform: "uppercase", fontFamily: "monospace", color: "#6b7280", marginBottom: "1rem" }}>DWS.07 · Platform error</p>
          <h1 style={{ fontSize: "1.5rem", fontWeight: 600, marginBottom: "0.75rem" }}>Something went wrong</h1>
          {/* eslint-disable-next-line dbp-local-hex/no-raw-design-values -- see body tag above: token CSS may not be loaded in this boundary. */}
          <p style={{ fontSize: "0.875rem", color: "#6b7280", marginBottom: "1.5rem" }}>
            An unexpected error occurred.{error.digest && <> Error ID: <code style={{ fontFamily: "monospace" }}>{error.digest}</code></>}
          </p>
          {/* eslint-disable-next-line dbp-local-hex/no-raw-design-values -- see body tag above: token CSS may not be loaded in this boundary. */}
          <button onClick={reset} style={{ padding: "0.5rem 1.25rem", fontSize: "0.875rem", fontWeight: 500, borderRadius: "6px", border: "none", backgroundColor: "#030F35", color: "#fff", cursor: "pointer" }}>Try again</button>
        </div>
      </body>
    </html>
  );
}
