import type { ReactNode } from "react";
import { Providers } from "./providers";
import { ToasterMount } from "./toaster-mount";
import "./globals.css";

export const metadata = {
  title: "BioTest Diagnostics Servicing",
  description: "Generated by DBP scaffold-solution — DWS.07",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body style={{ backgroundColor: "var(--color-surface)", color: "var(--color-text)" }}>
        <Providers>{children}</Providers>
        <ToasterMount />
      </body>
    </html>
  );
}
