// app/not-found.tsx — 404 page for DWS.07.
// Generated by scaffold-solution — do not edit (run with --force to regenerate).
import Link from "next/link";

export default function NotFound() {
  return (
    <div style={{ fontFamily: "system-ui, sans-serif", display: "flex", alignItems: "center", justifyContent: "center", minHeight: "100vh", backgroundColor: "var(--color-surface)", color: "var(--color-text)" }}>
      <div style={{ textAlign: "center", maxWidth: 480, padding: "2rem" }}>
        <p style={{ fontSize: "11px", letterSpacing: "0.14em", textTransform: "uppercase", fontFamily: "monospace", color: "var(--color-text-disabled)", marginBottom: "1rem" }}>DWS.07 · 404</p>
        <h1 style={{ fontSize: "1.5rem", fontWeight: 600, marginBottom: "0.75rem" }}>Page not found</h1>
        <p style={{ fontSize: "0.875rem", color: "var(--color-text-secondary)", marginBottom: "1.5rem" }}>The page you are looking for does not exist or has been moved.</p>
        <Link href="/home" style={{ display: "inline-block", padding: "0.5rem 1.25rem", fontSize: "0.875rem", fontWeight: 500, borderRadius: "6px", backgroundColor: "var(--color-primary)", color: "var(--color-primary-foreground)", textDecoration: "none" }}>Return to Home</Link>
      </div>
    </div>
  );
}
