// Root index — non-DXP solution: no public landing, redirect inward.
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { redirect } from "next/navigation";

export default function IndexPage() {
  redirect("/home");
}
