// Route → breadcrumb-trail map — Shell v2 Option 2 (breadcrumb-in-topbar).
// Generated by scaffold-solution — do not edit (run with --force to regenerate).
import type { BreadcrumbItem } from "@dbp/ui";

export const ROUTE_BREADCRUMBS: Record<string, BreadcrumbItem[]> = {
  "/dashboard": [
    {
      "label": "Orientation"
    },
    {
      "label": "Quick Links"
    },
    {
      "label": "My Dashboard"
    }
  ],
  "/my-work": [
    {
      "label": "Orientation"
    },
    {
      "label": "Quick Links"
    },
    {
      "label": "My Work"
    }
  ],
  "/transactions/enquiries": [
    {
      "label": "Marketplace"
    },
    {
      "label": "Transactions"
    },
    {
      "label": "Enquiries"
    }
  ],
  "/transactions/requests": [
    {
      "label": "Marketplace"
    },
    {
      "label": "Transactions"
    },
    {
      "label": "Requests"
    }
  ],
  "/transactions/support-tickets": [
    {
      "label": "Marketplace"
    },
    {
      "label": "Transactions"
    },
    {
      "label": "Support Tickets"
    }
  ],
  "/transactions/wallet": [
    {
      "label": "Marketplace"
    },
    {
      "label": "Transactions"
    },
    {
      "label": "Wallet"
    }
  ],
  "/collaboration/calendar": [
    {
      "label": "Marketplace"
    },
    {
      "label": "Collaboration"
    },
    {
      "label": "Calendar"
    }
  ],
  "/collaboration/forums": [
    {
      "label": "Marketplace"
    },
    {
      "label": "Collaboration"
    },
    {
      "label": "Forums"
    }
  ],
  "/manage-work/cases": [
    {
      "label": "Workspace"
    },
    {
      "label": "Manage Work"
    },
    {
      "label": "Cases"
    }
  ],
  "/manage-work/assignments": [
    {
      "label": "Workspace"
    },
    {
      "label": "Manage Work"
    },
    {
      "label": "Assignments"
    }
  ],
  "/manage-work/reviews": [
    {
      "label": "Workspace"
    },
    {
      "label": "Manage Work"
    },
    {
      "label": "Reviews"
    }
  ],
  "/manage-work/escalations": [
    {
      "label": "Workspace"
    },
    {
      "label": "Manage Work"
    },
    {
      "label": "Escalations"
    }
  ],
  "/monitor-work/queue": [
    {
      "label": "Workspace"
    },
    {
      "label": "Monitor Work"
    },
    {
      "label": "Work Queue"
    }
  ],
  "/monitor-work/alerts": [
    {
      "label": "Workspace"
    },
    {
      "label": "Monitor Work"
    },
    {
      "label": "Alerts"
    }
  ],
  "/manage-services/catalogue": [
    {
      "label": "Service Operations"
    },
    {
      "label": "Manage Services"
    },
    {
      "label": "Service Catalogue"
    }
  ],
  "/manage-services/requests": [
    {
      "label": "Service Operations"
    },
    {
      "label": "Manage Services"
    },
    {
      "label": "Service Requests"
    }
  ],
  "/manage-services/lifecycle": [
    {
      "label": "Service Operations"
    },
    {
      "label": "Manage Services"
    },
    {
      "label": "Service Lifecycle"
    }
  ],
  "/manage-services/quality": [
    {
      "label": "Service Operations"
    },
    {
      "label": "Manage Services"
    },
    {
      "label": "Service Quality"
    }
  ],
  "/manage-relationships/customers": [
    {
      "label": "Service Operations"
    },
    {
      "label": "Manage Relationships"
    },
    {
      "label": "Customers / Participants"
    }
  ],
  "/manage-relationships/partners": [
    {
      "label": "Service Operations"
    },
    {
      "label": "Manage Relationships"
    },
    {
      "label": "Partners"
    }
  ],
  "/manage-relationships/providers": [
    {
      "label": "Service Operations"
    },
    {
      "label": "Manage Relationships"
    },
    {
      "label": "Providers"
    }
  ],
  "/manage-relationships/accounts": [
    {
      "label": "Service Operations"
    },
    {
      "label": "Manage Relationships"
    },
    {
      "label": "Account Management"
    }
  ],
  "/manage-delivery/plans": [
    {
      "label": "Service Operations"
    },
    {
      "label": "Manage Delivery"
    },
    {
      "label": "Delivery Plans"
    }
  ],
  "/manage-delivery/tasks": [
    {
      "label": "Service Operations"
    },
    {
      "label": "Manage Delivery"
    },
    {
      "label": "Tasks"
    }
  ],
  "/manage-delivery/cases": [
    {
      "label": "Service Operations"
    },
    {
      "label": "Manage Delivery"
    },
    {
      "label": "Cases"
    }
  ],
  "/manage-delivery/incidents": [
    {
      "label": "Service Operations"
    },
    {
      "label": "Manage Delivery"
    },
    {
      "label": "Incidents"
    }
  ],
  "/manage-delivery/escalations": [
    {
      "label": "Service Operations"
    },
    {
      "label": "Manage Delivery"
    },
    {
      "label": "Escalations"
    }
  ],
  "/manage-delivery/fulfilment": [
    {
      "label": "Service Operations"
    },
    {
      "label": "Manage Delivery"
    },
    {
      "label": "Fulfilment Tracking"
    }
  ],
  "/dashboards/operational": [
    {
      "label": "Operational Intelligence"
    },
    {
      "label": "Dashboards"
    },
    {
      "label": "Operational Dashboards"
    }
  ],
  "/dashboards/executive": [
    {
      "label": "Operational Intelligence"
    },
    {
      "label": "Dashboards"
    },
    {
      "label": "Executive Dashboards"
    }
  ],
  "/dashboards/custom": [
    {
      "label": "Operational Intelligence"
    },
    {
      "label": "Dashboards"
    },
    {
      "label": "Custom Dashboards"
    }
  ],
  "/dashboards/alerts": [
    {
      "label": "Operational Intelligence"
    },
    {
      "label": "Dashboards"
    },
    {
      "label": "Alerts & Notifications"
    }
  ],
  "/dashboards/scorecards": [
    {
      "label": "Operational Intelligence"
    },
    {
      "label": "Dashboards"
    },
    {
      "label": "KPI Scorecards"
    }
  ],
  "/analytics/adhoc": [
    {
      "label": "Operational Intelligence"
    },
    {
      "label": "Analytics"
    },
    {
      "label": "Ad-hoc Analysis"
    }
  ],
  "/analytics/trends": [
    {
      "label": "Operational Intelligence"
    },
    {
      "label": "Analytics"
    },
    {
      "label": "Trend Analysis"
    }
  ],
  "/analytics/root-cause": [
    {
      "label": "Operational Intelligence"
    },
    {
      "label": "Analytics"
    },
    {
      "label": "Root Cause Analysis"
    }
  ],
  "/analytics/cohort": [
    {
      "label": "Operational Intelligence"
    },
    {
      "label": "Analytics"
    },
    {
      "label": "Cohort Analysis"
    }
  ],
  "/analytics/benchmarking": [
    {
      "label": "Operational Intelligence"
    },
    {
      "label": "Analytics"
    },
    {
      "label": "Benchmarking"
    }
  ],
  "/reports/standard": [
    {
      "label": "Operational Intelligence"
    },
    {
      "label": "Reports"
    },
    {
      "label": "Standard Reports"
    }
  ],
  "/reports/custom": [
    {
      "label": "Operational Intelligence"
    },
    {
      "label": "Reports"
    },
    {
      "label": "Custom Reports"
    }
  ],
  "/reports/scheduled": [
    {
      "label": "Operational Intelligence"
    },
    {
      "label": "Reports"
    },
    {
      "label": "Scheduled Reports"
    }
  ],
  "/reports/subscriptions": [
    {
      "label": "Operational Intelligence"
    },
    {
      "label": "Reports"
    },
    {
      "label": "Report Subscriptions"
    }
  ],
  "/reports/export": [
    {
      "label": "Operational Intelligence"
    },
    {
      "label": "Reports"
    },
    {
      "label": "Export & Sharing"
    }
  ],
  "/admin/organisation": [
    {
      "label": "Platform Management"
    },
    {
      "label": "General"
    },
    {
      "label": "Organisation Setup"
    }
  ],
  "/admin/workspace-settings": [
    {
      "label": "Platform Management"
    },
    {
      "label": "General"
    },
    {
      "label": "Workspace Settings"
    }
  ],
  "/admin/branding": [
    {
      "label": "Platform Management"
    },
    {
      "label": "General"
    },
    {
      "label": "Branding"
    }
  ],
  "/admin/regional": [
    {
      "label": "Platform Management"
    },
    {
      "label": "General"
    },
    {
      "label": "Regional & Language"
    }
  ],
  "/admin/business-hours": [
    {
      "label": "Platform Management"
    },
    {
      "label": "General"
    },
    {
      "label": "Business Hours"
    }
  ],
  "/admin/defaults": [
    {
      "label": "Platform Management"
    },
    {
      "label": "General"
    },
    {
      "label": "Default Values"
    }
  ],
  "/admin/users": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Users & Access"
    },
    {
      "label": "User Management"
    }
  ],
  "/admin/roles": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Users & Access"
    },
    {
      "label": "Role Management"
    }
  ],
  "/admin/access-control": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Users & Access"
    },
    {
      "label": "Access Control"
    }
  ],
  "/admin/auth": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Users & Access"
    },
    {
      "label": "Authentication Settings"
    }
  ],
  "/admin/form-builder": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Processes & Automation"
    },
    {
      "label": "Form Builder"
    }
  ],
  "/admin/workflow-builder": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Processes & Automation"
    },
    {
      "label": "Workflow Builder"
    }
  ],
  "/admin/rules": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Processes & Automation"
    },
    {
      "label": "Rule Management"
    }
  ],
  "/admin/data-model": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Data & Structure"
    },
    {
      "label": "Data Model"
    }
  ],
  "/admin/master-data": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Data & Structure"
    },
    {
      "label": "Master Data"
    }
  ],
  "/admin/reference-data": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Data & Structure"
    },
    {
      "label": "Reference Data"
    }
  ],
  "/admin/data-quality": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Data & Structure"
    },
    {
      "label": "Data Quality Rules"
    }
  ],
  "/admin/data-lineage": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Data & Structure"
    },
    {
      "label": "Data Lineage"
    }
  ],
  "/admin/apis": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Integrations"
    },
    {
      "label": "API Management"
    }
  ],
  "/admin/connectors": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Integrations"
    },
    {
      "label": "Connectors"
    }
  ],
  "/admin/data-flows": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Integrations"
    },
    {
      "label": "Data Flows"
    }
  ],
  "/admin/data-import": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Integrations"
    },
    {
      "label": "Data Import"
    }
  ],
  "/admin/policies": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Platform"
    },
    {
      "label": "Policy Management"
    }
  ],
  "/admin/controls": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Platform"
    },
    {
      "label": "Control Register"
    }
  ],
  "/admin/risks": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Platform"
    },
    {
      "label": "Risk Register"
    }
  ],
  "/admin/security-logs": [
    {
      "label": "Platform Management"
    },
    {
      "label": "Platform"
    },
    {
      "label": "Security Logs"
    }
  ],
  "/servicing": [
    {
      "label": "Servicing Queue"
    }
  ],
  "/marketplace/discern": [
    {
      "label": "Marketplace"
    },
    {
      "label": "Catalogue"
    },
    {
      "label": "Imaging & Radiology"
    }
  ],
  "/marketplace/design": [
    {
      "label": "Marketplace"
    },
    {
      "label": "Catalogue"
    },
    {
      "label": "Diagnostic Procedures"
    }
  ],
  "/marketplace/deploy": [
    {
      "label": "Marketplace"
    },
    {
      "label": "Catalogue"
    },
    {
      "label": "Sample Collection"
    }
  ],
  "/marketplace/drive": [
    {
      "label": "Marketplace"
    },
    {
      "label": "Catalogue"
    },
    {
      "label": "Back Office"
    }
  ],
  "/copilot": [
    {
      "label": "DWS.07",
      "href": "/"
    },
    {
      "label": "AI Cockpit"
    }
  ]
};

/** Longest-prefix match against ROUTE_BREADCRUMBS (handles /route/:id sub-paths). */
export function resolveBreadcrumb(pathname: string): BreadcrumbItem[] | undefined {
  if (ROUTE_BREADCRUMBS[pathname]) return ROUTE_BREADCRUMBS[pathname];
  const candidates = Object.keys(ROUTE_BREADCRUMBS)
    .filter((route) => pathname.startsWith(route + "/"))
    .sort((a, b) => b.length - a.length);
  const best = candidates[0];
  return best !== undefined ? ROUTE_BREADCRUMBS[best] : undefined;
}
