"use client";
// Connected app chrome — the enriched, session + capability driven top bar.
// Generated by scaffold-solution — do not edit (run with --force to regenerate).
//
// Built ONCE and inherited by every shell-mounting page (home / marketplace /
// copilot / modules). Nothing is hardcoded:
//   • identity      ← PS.AUTH session via useSessionIdentity()
//   • search        ← @dbp/organisms/search-bar mounted into AppChrome's search
//     slot only when PS.SEARCH is wired (HAS_SEARCH below) — AppChrome itself
//     never imports the organism (Layer 06/07 boundary; component-architecture-
//     standard.md §7b / Amendment D-2 rollout, 2026-07-21).
//   • bell          ← @dbp/organisms/notification-bell mounted into AppChrome's
//     notifications slot only when PS.NOTIF is wired (HAS_NOTIF below)
//   • lockup        ← solution code + name from the manifest
//   • breadcrumb    ← derived from the current pathname via ROUTE_BREADCRUMBS
//     (Shell v2 Option 2 — see docs/09-plans/shell-v2-option2-implementation-2026-07-17.md)
import * as React from "react";
import { useRouter, usePathname } from "next/navigation";
import { useSessionIdentity } from "@dbp/ps-auth/client";
import { AppChrome } from "@dbp/ui";
import { TenantSwitcher } from "@dbp/organisms/tenant-switcher";
import { SearchBar } from "@dbp/organisms/search-bar";
import { NotificationBell } from "@dbp/organisms/notification-bell";
import { resolveBreadcrumb } from "./route-breadcrumbs";

const PRODUCT_CODE = "DWS.07";
const PRODUCT_NAME = "BioTest Diagnostics Servicing";



export interface SolutionChromeProps {
  /** Optional global-search placeholder override (per route). */
  searchPlaceholder?: string;
}

export function SolutionChrome({ searchPlaceholder }: SolutionChromeProps) {
  const router = useRouter();
  const pathname = usePathname();
  const { identity } = useSessionIdentity();
  const breadcrumb = resolveBreadcrumb(pathname ?? "");
  return (
    <AppChrome
      productCode={PRODUCT_CODE}
      productName={PRODUCT_NAME}
      
      
      session={identity}
      {...(breadcrumb !== undefined ? { breadcrumb } : {})}
      search={
        <SearchBar
          {...(searchPlaceholder !== undefined ? { placeholder: searchPlaceholder } : {})}
          onSelect={(hit) => router.push("/marketplace/" + encodeURIComponent(hit.id))}
        />
      }
      notifications={<NotificationBell />}
    />
  );
}

// N30 ruling: the sidebar identity block IS the workspace/tenant switcher —
// mounted via TransactionShell's nav.identitySlot (see authenticated-client-shell.tsx).
// @dbp/ui stays auth-free; this wrapper supplies the session-derived tenant id,
// same pattern as SolutionChrome above.
export function SolutionSidebarSwitcher({ collapsed }: { collapsed?: boolean }) {
  const { identity } = useSessionIdentity();
  if (!identity) return null;
  return (
    <TenantSwitcher
      currentTenantId={identity.tenantId}
      solutionName={PRODUCT_NAME}
      {...(collapsed !== undefined ? { collapsed } : {})}
    />
  );
}
