"use client";
// Connected app footer — the full-width workspace status bar.
// Generated by scaffold-solution — do not edit (run with --force to regenerate).
//
// Built ONCE and inherited by every shell-mounting page via nav.footer.
// Content is a pure projection of manifest.footer (productName falls back to the
// solution name). Keep it compact and muted — workspace chrome, not marketing.
// When manifest.footer.shortcuts are declared, the SAME list both renders the
// hints AND is installed as live keyboard shortcuts.
import { useRouter } from "next/navigation";
import { AppFooter, useKeyboardShortcuts } from "@dbp/ui";

const SHORTCUTS = [
  {
    "keys": "⌘K",
    "label": "Search"
  },
  {
    "keys": "G H",
    "label": "Home",
    "href": "/home"
  }
];

export function SolutionFooter() {
  const router = useRouter();
  useKeyboardShortcuts(SHORTCUTS, { onNavigate: (href) => router.push(href) });
  return (
    <AppFooter
      productName={"BioTest Diagnostics Servicing"}
      copyright={"© 2026 BioTest Diagnostics Servicing"}
      version={"v1.0.0"}
      shortcuts={SHORTCUTS}
    />
  );
}
