// Generated by scaffold-solution — do not edit.
// All rules live in @dbp/config (boundary matrix + design-system rules); this file
// only composes the presets so rule updates arrive via a @dbp/config version bump.
// dqDesignRules/maxLinesConfig are re-scoped to this app's own trees because a
// standalone repo has the app at its root — the preset's monorepo apps/** globs
// never match here. maxLinesConfig deliberately excludes app/** (generator-owned
// chrome/pages/route config, per ADR-0050) — only solution/** is hand-authored.
import dbp, { dqDesignRules, maxLinesConfig } from "@dbp/config/eslint";
import dbpNextjs from "@dbp/config/eslint/nextjs";

export default [
  ...dbp,
  ...dbpNextjs,
  ...dqDesignRules(["app/**/*.{ts,tsx}", "solution/**/*.{ts,tsx}", "components/**/*.{ts,tsx}", "lib/**/*.{ts,tsx}"]),
  ...maxLinesConfig(["solution/**/*.{ts,tsx}", "instrumentation.ts", "instrumentation.node.ts"]),
];
