// Generated by scaffold-solution — do not edit.
// UX shell audit config — standalone version, this repo IS the app root. Separate
// from playwright.a11y.config.ts because this gate needs a full authenticated
// walkthrough (login + every nav route), not just the unauthenticated /login page.
import { defineConfig, devices } from "@playwright/test";

const PORT = 3001;
const BASE_URL = `http://localhost:${PORT}`;

export default defineConfig({
  testDir: "./e2e",
  testMatch: "ux-shell-audit.spec.ts",
  fullyParallel: false,
  forbidOnly: !!process.env["CI"],
  retries: 0,
  workers: 1,
  reporter: [["list"]],
  use: {
    baseURL: BASE_URL,
    trace: "on-first-retry",
  },
  outputDir: "workspace/ux-audit-artifacts",
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
  webServer: {
    command: `node node_modules/next/dist/bin/next start -p ${PORT}`,
    cwd: ".",
    url: `${BASE_URL}/login`,
    reuseExistingServer: true,
    timeout: 120_000,
    stdout: "pipe",
    stderr: "pipe",
    env: {
      DBP_AUTH_SESSION_SECRET: "ux-audit-gate-dev-secret-not-for-production-0000000000",
    },
  },
});
