// Generated by scaffold-solution — do not edit.
// N5 a11y smoke gate config. Standalone version of the monorepo's playwright.a11y.config.ts —
// this repo IS the app root, so the webServer runs from "." instead of an apps/<id> subdir.
import { defineConfig, devices } from "@playwright/test";

const PORT = 3231;
const BASE_URL = `http://localhost:${PORT}`;

export default defineConfig({
  testDir: "./e2e",
  testMatch: "a11y.spec.ts",
  fullyParallel: false,
  forbidOnly: !!process.env["CI"],
  retries: 0,
  workers: 1,
  reporter: [["list"]],
  use: {
    baseURL: BASE_URL,
    trace: "on-first-retry",
  },
  outputDir: "workspace/a11y-artifacts",
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
  webServer: {
    command: `node node_modules/next/dist/bin/next start -p ${PORT}`,
    cwd: ".",
    url: `${BASE_URL}/login`,
    reuseExistingServer: true,
    timeout: 120_000,
    stdout: "pipe",
    stderr: "pipe",
    env: {
      DBP_AUTH_SESSION_SECRET: "a11y-gate-dev-secret-not-for-production-0000000000",
    },
  },
});
