// Generated by scaffold-solution — do not edit.
// Default environment is node (route/adapter tests). Component tests opt into the
// DOM per file with the pragma comment `// @vitest-environment jsdom` on line 1 —
// the emitted solution/pages test stubs carry it already.
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["**/*.test.{ts,tsx}"],
    exclude: ["**/node_modules/**", "**/.next/**"],
    environment: "node",
    passWithNoTests: true,
  },
});
