"use client";
// Module: DWS.07.S57 — Data Model
// Shell: SH.02  Journey stage: 2
// Layout: canvas-workspace
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { CanvasLayout } from "@dbp/shell-transaction/layouts";
import { Button } from "@dbp/ui";
import EntityList from "@dbp/organisms/entity-list";

export default function DataModelPage() {
  return (
      <CanvasLayout>
        <div className="flex justify-end gap-2 mb-4">
          <Button variant="navy" onClick={() => {}}>New Data Model</Button>
        </div>
        <EntityList
          key="admin-data-model-list"
          {...({
            entityType: "demo-record",
            columns: [
              { field: "name", label: "Name", sortable: true },
              { field: "status", label: "Status", sortable: true, format: "badge", badgeTones: { active: "success", invited: "info", disabled: "gray", suspended: "warning" } },
              { field: "owner", label: "Owner", sortable: true },
              { field: "updated", label: "Last Modified", sortable: true, format: "date" },
            ],
            pageSize: 20,
            enableSearch: true,
            listTabs: [
              { key: "all", label: "All", where: [] },
              { key: "open", label: "Open", where: [{ field: "status", op: "is", value: "active" }] },
              { key: "in-progress", label: "In Progress", where: [{ field: "status", op: "is", value: "invited" }] },
              { key: "review", label: "Review", where: [{ field: "status", op: "is", value: "disabled" }] },
              { key: "done", label: "Done", where: [{ field: "status", op: "is", value: "suspended" }] },
            ],
            detailHref: "/admin/data-model",
            detailDrawer: false,
          } as Parameters<typeof EntityList>[0])}
        />
      </CanvasLayout>
  );
}
