"use client";
// Module: DWS.07.S54 — Form Builder
// Shell: SH.02  Journey stage: 2
// Layout: collection-table
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { CanvasLayout } from "@dbp/shell-transaction/layouts";

export default function FormBuilderPage() {
  return (
      <CanvasLayout>
        <div className="flex flex-col items-center justify-center py-24 text-center px-6">
          <p className="text-xs font-mono tracking-widest uppercase text-[var(--color-text-muted)] mb-4">Deferred capability</p>
          <h2 className="text-lg font-semibold mb-2 text-[var(--color-text)]">Coming soon</h2>
          <p className="text-sm text-[var(--color-text-secondary)] max-w-sm">This capability is not yet available in this environment.</p>
        </div>
      </CanvasLayout>
  );
}
