// app/api/health/route.ts — liveness probe for DWS.07.
// Generated by scaffold-solution — do not edit (run with --force to regenerate).
import { NextResponse } from "next/server";

export const runtime = "edge";

export function GET() {
  return NextResponse.json(
    { status: "ok", solution: "DWS.07", timestamp: new Date().toISOString() },
    { status: 200, headers: { "Cache-Control": "no-store" } },
  );
}
