"use client";
// app/(public)/error.tsx — segment error boundary for public routes.
// Generated by scaffold-solution — do not edit (run with --force to regenerate).
import { useEffect } from "react";

export default function PublicError({
  error,
  reset,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  useEffect(() => {
    console.error("[DWS.07] public segment error:", error);
  }, [error]);

  return (
    <div style={{ display: "flex", alignItems: "center", justifyContent: "center", minHeight: "60vh", padding: "2rem", color: "var(--color-text)" }}>
      <div style={{ textAlign: "center", maxWidth: 420 }}>
        <p style={{ fontSize: "11px", letterSpacing: "0.14em", textTransform: "uppercase", fontFamily: "monospace", color: "var(--color-text-disabled)", marginBottom: "0.75rem" }}>
          DWS.07 · Error
        </p>
        <h2 style={{ fontSize: "1.25rem", fontWeight: 600, marginBottom: "0.5rem" }}>Something went wrong</h2>
        <p style={{ fontSize: "0.875rem", color: "var(--color-text-secondary)", marginBottom: "1.25rem" }}>
          An error occurred while loading this page.
          {error.digest && <> Ref: <code style={{ fontFamily: "monospace", fontSize: "0.75rem" }}>{error.digest}</code></>}
        </p>
        <button
          onClick={reset}
          style={{ padding: "0.4rem 1rem", fontSize: "0.875rem", fontWeight: 500, borderRadius: "var(--radius-button, 6px)", border: "1px solid var(--color-border)", backgroundColor: "var(--color-surface)", color: "var(--color-text)", cursor: "pointer" }}
        >
          Try again
        </button>
      </div>
    </div>
  );
}
