import type { ReactNode } from "react";

// Public route-group layout — passthrough wrapper.
// Pages under app/(public)/** (e.g. /login) are rendered without the
// TransactionShell so unauthenticated users see only the page content.
// Generated by scaffold-solution — do not edit (run with --force to regenerate).
export default function PublicLayout({ children }: { children: ReactNode }) {
  return <>{children}</>;
}
