// app/(public)/loading.tsx — public-segment Suspense skeleton.
// Generated by scaffold-solution — do not edit (run with --force to regenerate).
export default function PublicLoading() {
  return (
    <div aria-label="Loading" aria-busy="true" style={{ padding: "1.5rem", display: "flex", flexDirection: "column", gap: "0.75rem" }}>
      <div style={{ height: "20px", width: "30%", borderRadius: "4px", background: "color-mix(in srgb, var(--color-border) 60%, var(--color-surface))", animation: "pulse 1.5s ease-in-out infinite" }} />
      {[80, 65, 72, 55].map((w, i) => (
        <div key={i} style={{ height: "14px", width: `${w}%`, borderRadius: "4px", background: "color-mix(in srgb, var(--color-border) 60%, var(--color-surface))", animation: `pulse 1.5s ease-in-out ${i * 0.1}s infinite` }} />
      ))}
      <style>{`@keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }`}</style>
    </div>
  );
}
