"use client";
// Module: DWS.07.S29 — Operational Dashboards
// Shell: SH.02  Journey stage: 2
// Layout: analytics-dashboard
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { AnalyticsLayout } from "@dbp/shell-transaction/layouts";
import KpiScorecard from "@dbp/organisms/kpi-scorecard";
import ChartPanel from "@dbp/organisms/chart-panel";

export default function OperationalDashboardsPage() {
  return (
      <AnalyticsLayout
      >
        <div className="flex flex-col gap-6">
        <KpiScorecard
          key="operational-intelligence-operational-dashboards-scorecard"
          {...({
        "layout": "grid",
        "kpis": [
                {
                        "id": "operational-intelligence-operational-dashboards-open",
                        "label": "Open",
                        "entityType": "demo-record",
                        "metric": {
                                "aggregate": "count"
                        },
                        "filters": {
                                "status": "open"
                        },
                        "format": "number",
                        "icon": "Activity"
                },
                {
                        "id": "operational-intelligence-operational-dashboards-in-progress",
                        "label": "In Progress",
                        "entityType": "demo-record",
                        "metric": {
                                "aggregate": "count"
                        },
                        "filters": {
                                "status": "in-progress"
                        },
                        "format": "number",
                        "icon": "Hash"
                },
                {
                        "id": "operational-intelligence-operational-dashboards-review",
                        "label": "Review",
                        "entityType": "demo-record",
                        "metric": {
                                "aggregate": "count"
                        },
                        "filters": {
                                "status": "review"
                        },
                        "format": "number",
                        "icon": "Target"
                },
                {
                        "id": "operational-intelligence-operational-dashboards-done",
                        "label": "Done",
                        "entityType": "demo-record",
                        "metric": {
                                "aggregate": "count"
                        },
                        "filters": {
                                "status": "done"
                        },
                        "format": "number",
                        "icon": "TrendingUp"
                }
        ]
} as Parameters<typeof KpiScorecard>[0])}
        />
        <ChartPanel
          key="operational-intelligence-operational-dashboards-chart"
          {...({
        "title": "Lab Service by Category",
        "entityType": "lab-service",
        "chartType": "bar",
        "categoryField": "category",
        "series": [
                {
                        "valueField": "id",
                        "label": "Lab Services",
                        "aggregate": "count"
                }
        ],
        "height": 300
} as Parameters<typeof ChartPanel>[0])}
        />
        <ChartPanel
          key="operational-intelligence-operational-dashboards-funnel"
          {...({
        "title": "Lab Service Pipeline",
        "entityType": "lab-service",
        "chartType": "funnel",
        "categoryField": "status",
        "series": [
                {
                        "valueField": "id",
                        "label": "Lab Services",
                        "aggregate": "count"
                }
        ],
        "height": 220
} as Parameters<typeof ChartPanel>[0])}
        />
        <ChartPanel
          key="operational-intelligence-operational-dashboards-ranking"
          {...({
        "title": "Category Ranking",
        "entityType": "lab-service",
        "chartType": "ranking",
        "categoryField": "category",
        "series": [
                {
                        "valueField": "id",
                        "label": "Lab Services",
                        "aggregate": "count"
                }
        ],
        "height": 220
} as Parameters<typeof ChartPanel>[0])}
        />
        </div>
      </AnalyticsLayout>
  );
}
