"use client";
// Module: DWS.07.S45 — Workspace Settings
// Shell: SH.02  Journey stage: 2
// Layout: config-form-single
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { SettingsLayout } from "@dbp/shell-transaction/layouts";
import { Button } from "@dbp/ui";
import { AdminSettingsForm } from "@dbp/ui";
import type { AdminSettingsFormSection } from "@dbp/ui";
import { SettingsNav } from "@dbp/ui";

export default function WorkspaceSettingsPage() {
  return (
      <SettingsLayout
        nav={<SettingsNav links={[{"href":"/admin/organisation","label":"Organisation Setup"},{"href":"/admin/workspace-settings","label":"Workspace Settings"},{"href":"/admin/branding","label":"Branding"},{"href":"/admin/regional","label":"Regional & Language"},{"href":"/admin/business-hours","label":"Business Hours"},{"href":"/admin/defaults","label":"Default Values"},{"href":"/admin/users","label":"User Management"},{"href":"/admin/roles","label":"Role Management"},{"href":"/admin/access-control","label":"Access Control"},{"href":"/admin/auth","label":"Authentication Settings"},{"href":"/admin/form-builder","label":"Form Builder"},{"href":"/admin/workflow-builder","label":"Workflow Builder"},{"href":"/admin/rules","label":"Rule Management"},{"href":"/admin/data-model","label":"Data Model"},{"href":"/admin/master-data","label":"Master Data"},{"href":"/admin/reference-data","label":"Reference Data"},{"href":"/admin/data-quality","label":"Data Quality Rules"},{"href":"/admin/data-lineage","label":"Data Lineage"},{"href":"/admin/apis","label":"API Management"},{"href":"/admin/connectors","label":"Connectors"},{"href":"/admin/data-flows","label":"Data Flows"},{"href":"/admin/data-import","label":"Data Import"},{"href":"/admin/policies","label":"Policy Management"},{"href":"/admin/controls","label":"Control Register"},{"href":"/admin/risks","label":"Risk Register"},{"href":"/admin/security-logs","label":"Security Logs"}]} />}
      >
        <div className="flex justify-end gap-2 mb-4">
          <Button variant="navy" onClick={() => (document.getElementById("admin-workspace-settings") as HTMLFormElement | null)?.requestSubmit()}>Save changes</Button>
        </div>
        <AdminSettingsForm formId="admin-workspace-settings" sections={[
        {
                "title": "Workspace",
                "fields": [
                        {
                                "name": "workspace-name",
                                "label": "Workspace name",
                                "fieldType": "text"
                        },
                        {
                                "name": "default-landing",
                                "label": "Default landing page",
                                "fieldType": "select",
                                "defaultValue": "/home",
                                "options": [
                                        {
                                                "value": "/home",
                                                "label": "Home"
                                        },
                                        {
                                                "value": "/dashboard",
                                                "label": "My Dashboard"
                                        },
                                        {
                                                "value": "/my-work",
                                                "label": "My Work"
                                        }
                                ]
                        },
                        {
                                "name": "allow-personal-views",
                                "label": "Allow personal saved views",
                                "fieldType": "switch",
                                "defaultChecked": true
                        }
                ]
        }
] as AdminSettingsFormSection[]} />
      </SettingsLayout>
  );
}
