"use client";
// Module: DWS.07.M01 — Servicing Queue
// Shell: SH.03  Journey stage: 3
// Layout: lve-split
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import * as React from "react";
import { CanvasLayout } from "@dbp/shell-transaction/layouts";
import LveWorkspace from "@dbp/organisms/lve-workspace";
import KpiScorecard from "@dbp/organisms/kpi-scorecard";

export default function ServicingQueuePage() {
  // Track LVE view mode — feeds callbacks.onViewChange on <LveWorkspace> (ADR-0040).
  const [, setLveListMode] = React.useState(true);

  return (
      <CanvasLayout
        fullBleed
      >
        <div className="flex flex-col gap-6">
        <div className="-mx-[var(--shell-gutter)] -mb-[var(--shell-gutter)] h-[calc(100%+var(--shell-gutter))] flex flex-col">
          <LveWorkspace
          key="servicing-queue"
          {...({
        "entityType": "exam-order",
        "entityLabel": "Exam Order",
        "columns": [
                {
                        "field": "patientName",
                        "label": "Patient",
                        "sortable": true
                },
                {
                        "field": "department",
                        "label": "Department",
                        "sortable": true
                },
                {
                        "field": "source",
                        "label": "Source",
                        "sortable": true
                },
                {
                        "field": "status",
                        "label": "Status",
                        "sortable": true,
                        "format": "badge",
                        "badgeTones": {
                                "in-progress": "warning",
                                "released": "success",
                                "recapture-requested": "danger"
                        }
                }
        ],
        "pageSize": 25,
        "enableSearch": true,
        "selectable": true,
        "header": {
                "titleField": "patientName",
                "subtitleField": "serviceCode",
                "statusField": "status"
        },
        "detailTabs": [
                {
                        "id": "details",
                        "label": "Order Details",
                        "sections": [
                                {
                                        "title": "Order Details",
                                        "fields": [
                                                {
                                                        "field": "patientName",
                                                        "label": "Patient",
                                                        "format": "text"
                                                },
                                                {
                                                        "field": "patientPhone",
                                                        "label": "Phone",
                                                        "format": "text"
                                                },
                                                {
                                                        "field": "source",
                                                        "label": "Source"
                                                },
                                                {
                                                        "field": "department",
                                                        "label": "Department"
                                                },
                                                {
                                                        "field": "serviceCode",
                                                        "label": "Service"
                                                },
                                                {
                                                        "field": "siteId",
                                                        "label": "Site"
                                                },
                                                {
                                                        "field": "notes",
                                                        "label": "Notes",
                                                        "format": "text",
                                                        "editable": true,
                                                        "editType": "text"
                                                }
                                        ]
                                }
                        ]
                }
        ],
        "quickActions": [
                {
                        "action": "release",
                        "label": "Release",
                        "when": [
                                {
                                        "field": "status",
                                        "op": "is",
                                        "value": "in-progress"
                                }
                        ],
                        "patch": {
                                "status": "released"
                        },
                        "tone": "success"
                },
                {
                        "action": "recapture",
                        "label": "Request Recapture",
                        "when": [
                                {
                                        "field": "status",
                                        "op": "is",
                                        "value": "in-progress"
                                }
                        ],
                        "patch": {
                                "status": "recapture-requested"
                        },
                        "tone": "warning"
                },
                {
                        "action": "back-to-progress",
                        "label": "Back to In Progress",
                        "when": [
                                {
                                        "field": "status",
                                        "op": "is",
                                        "value": "recapture-requested"
                                }
                        ],
                        "patch": {
                                "status": "in-progress"
                        },
                        "tone": "default"
                }
        ],
        "showActivity": true,
        "createConfig": {
                "title": "New Exam Order",
                "fields": [
                        {
                                "field": "patientName",
                                "label": "Patient Name",
                                "editType": "text",
                                "required": true
                        },
                        {
                                "field": "patientPhone",
                                "label": "Patient Phone",
                                "editType": "text",
                                "required": true
                        },
                        {
                                "field": "source",
                                "label": "Source",
                                "editType": "select",
                                "required": true,
                                "editOptions": [
                                        {
                                                "value": "walk-in",
                                                "label": "Walk-in"
                                        },
                                        {
                                                "value": "dxp",
                                                "label": "Patient App"
                                        },
                                        {
                                                "value": "referral",
                                                "label": "Referral"
                                        }
                                ]
                        },
                        {
                                "field": "department",
                                "label": "Department",
                                "editType": "select",
                                "required": true,
                                "editOptions": [
                                        {
                                                "value": "imaging",
                                                "label": "Imaging & Radiology"
                                        },
                                        {
                                                "value": "diagnostic-procedures",
                                                "label": "Diagnostic Procedures"
                                        },
                                        {
                                                "value": "sample-collection",
                                                "label": "Sample Collection"
                                        },
                                        {
                                                "value": "back-office",
                                                "label": "Back Office"
                                        }
                                ]
                        },
                        {
                                "field": "serviceCode",
                                "label": "Service Code",
                                "editType": "text",
                                "required": true
                        },
                        {
                                "field": "siteId",
                                "label": "Site",
                                "editType": "text",
                                "required": true
                        }
                ],
                "defaults": {
                        "status": "in-progress"
                }
        },
        "externalHeader": true,
        "listTabs": [
                {
                        "key": "all",
                        "label": "All"
                }
        ]
} as Parameters<typeof LveWorkspace>[0])}
          callbacks={{ onViewChange: (mode) => setLveListMode(mode === "list") }}
        /></div>
        <KpiScorecard
          key="servicing-kpis"
          {...({
        "layout": "grid",
        "kpis": [
                {
                        "id": "in-progress",
                        "label": "In Progress",
                        "entityType": "exam-order",
                        "metric": {
                                "aggregate": "count"
                        },
                        "filters": {
                                "status": "in-progress"
                        },
                        "format": "number",
                        "icon": "Activity",
                        "tone": "warning"
                },
                {
                        "id": "released",
                        "label": "Released",
                        "entityType": "exam-order",
                        "metric": {
                                "aggregate": "count"
                        },
                        "filters": {
                                "status": "released"
                        },
                        "format": "number",
                        "icon": "Target",
                        "tone": "success"
                },
                {
                        "id": "recapture",
                        "label": "Recapture Requested",
                        "entityType": "exam-order",
                        "metric": {
                                "aggregate": "count"
                        },
                        "filters": {
                                "status": "recapture-requested"
                        },
                        "format": "number",
                        "icon": "TrendingUp",
                        "tone": "info"
                }
        ]
} as Parameters<typeof KpiScorecard>[0])}
        />
        </div>
      </CanvasLayout>
  );
}
