"use client";
// Module: DWS.07.S04 — Requests
// Shell: SH.02  Journey stage: 2
// Layout: object-page-detail
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { CanvasLayout } from "@dbp/shell-transaction/layouts";
import EntityList from "@dbp/organisms/entity-list";

export default function RequestsPage() {
  return (
      <CanvasLayout
      >
        <EntityList
          key="marketplace-requests"
          {...({
        "entityType": "service-offering-request",
        "columns": [
                {
                        "field": "serviceId",
                        "label": "ServiceId",
                        "sortable": true,
                        "editable": true,
                        "editType": "text"
                },
                {
                        "field": "description",
                        "label": "Description",
                        "sortable": true,
                        "editable": true,
                        "editType": "text"
                },
                {
                        "field": "urgency",
                        "label": "Urgency",
                        "sortable": true,
                        "editable": true,
                        "editType": "select",
                        "editOptions": [
                                {
                                        "value": "low",
                                        "label": "Low"
                                },
                                {
                                        "value": "medium",
                                        "label": "Medium"
                                },
                                {
                                        "value": "high",
                                        "label": "High"
                                }
                        ]
                },
                {
                        "field": "justification",
                        "label": "Justification",
                        "sortable": true,
                        "editable": true,
                        "editType": "text"
                }
        ],
        "pageSize": 15,
        "enableSearch": true,
        "listTabs": [
                {
                        "key": "all",
                        "label": "All",
                        "where": []
                },
                {
                        "key": "low",
                        "label": "Low",
                        "where": [
                                {
                                        "field": "urgency",
                                        "op": "is",
                                        "value": "low"
                                }
                        ]
                },
                {
                        "key": "medium",
                        "label": "Medium",
                        "where": [
                                {
                                        "field": "urgency",
                                        "op": "is",
                                        "value": "medium"
                                }
                        ]
                },
                {
                        "key": "high",
                        "label": "High",
                        "where": [
                                {
                                        "field": "urgency",
                                        "op": "is",
                                        "value": "high"
                                }
                        ]
                }
        ],
        "detailDrawer": {
                "titleField": "serviceId",
                "subtitleFields": [],
                "entityLabel": "Service Offering Request",
                "statusField": "urgency",
                "statusTones": {
                        "low": "info",
                        "medium": "info",
                        "high": "info"
                },
                "descriptionField": "description",
                "quickActions": [
                        {
                                "id": "mark-low",
                                "label": "Mark low",
                                "patch": {
                                        "urgency": "low"
                                }
                        }
                ],
                "headerMenu": [
                        {
                                "id": "mark-medium",
                                "label": "Mark medium",
                                "patch": {
                                        "urgency": "medium"
                                }
                        },
                        {
                                "id": "mark-high",
                                "label": "Mark high",
                                "patch": {
                                        "urgency": "high"
                                }
                        }
                ],
                "variants": {},
                "labels": {},
                "defaultSections": [
                        {
                                "id": "overview",
                                "title": "Overview",
                                "fields": [
                                        {
                                                "id": "serviceId",
                                                "label": "ServiceId",
                                                "format": "text",
                                                "editable": false
                                        },
                                        {
                                                "id": "description",
                                                "label": "Description",
                                                "format": "text",
                                                "editable": false
                                        },
                                        {
                                                "id": "urgency",
                                                "label": "Urgency",
                                                "format": "text",
                                                "render": "status-dot",
                                                "badgeTones": {
                                                        "low": "info",
                                                        "medium": "info",
                                                        "high": "info"
                                                },
                                                "editable": false
                                        },
                                        {
                                                "id": "justification",
                                                "label": "Justification",
                                                "format": "text",
                                                "editable": false
                                        }
                                ]
                        }
                ],
                "tabs": [
                        {
                                "id": "overview",
                                "label": "Overview",
                                "kind": "fields"
                        },
                        {
                                "id": "comments",
                                "label": "Comments",
                                "kind": "comments"
                        },
                        {
                                "id": "audit",
                                "label": "Audit",
                                "kind": "audit"
                        }
                ],
                "comments": {
                        "entityType": "service-offering-request"
                },
                "deepLink": true,
                "expandable": true
        }
} as Parameters<typeof EntityList>[0])}
        />
      </CanvasLayout>
  );
}
