"use client";
// Module: DWS.07.S27 — Escalations
// Shell: SH.02  Journey stage: 2
// Layout: object-page-detail
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import * as React from "react";
import { CanvasLayout } from "@dbp/shell-transaction/layouts";
import LveWorkspace from "@dbp/organisms/lve-workspace";

export default function EscalationsPage() {
  // Track LVE view mode — feeds callbacks.onViewChange on <LveWorkspace> (ADR-0040).
  const [, setLveListMode] = React.useState(true);

  return (
      <CanvasLayout
        fullBleed
      >
        <div className="-mx-[var(--shell-gutter)] -mb-[var(--shell-gutter)] h-[calc(100%+var(--shell-gutter))] flex flex-col">
          <LveWorkspace
          key="service-operations-delivery-escalations"
          {...({
        "entityType": "lab-service",
        "entityLabel": "Lab Service",
        "title": "Escalations",
        "externalHeader": true,
        "columns": [
                {
                        "field": "name",
                        "label": "Name",
                        "sortable": true
                },
                {
                        "field": "summary",
                        "label": "Summary",
                        "sortable": true
                },
                {
                        "field": "department",
                        "label": "Department",
                        "sortable": true
                },
                {
                        "field": "status",
                        "label": "Status",
                        "sortable": true
                },
                {
                        "field": "code",
                        "label": "Code",
                        "sortable": true
                },
                {
                        "field": "slaTargetHours",
                        "label": "SlaTargetHours",
                        "sortable": true
                }
        ],
        "pageSize": 25,
        "enableSearch": true,
        "enableSort": true,
        "sortFields": [
                "name",
                "summary",
                "department",
                "status"
        ],
        "showTabCounts": true,
        "listTabs": [
                {
                        "key": "all",
                        "label": "All",
                        "where": []
                }
        ],
        "detailMode": "list",
        "enableViewToggle": true,
        "enableRecordPager": true,
        "showSaveStatus": true,
        "header": {
                "titleField": "name",
                "statusField": "status"
        },
        "detailTabs": [
                {
                        "id": "details",
                        "label": "Details",
                        "sections": [
                                {
                                        "title": "Overview",
                                        "fields": [
                                                {
                                                        "field": "name",
                                                        "label": "Name",
                                                        "editable": true,
                                                        "editType": "text"
                                                },
                                                {
                                                        "field": "summary",
                                                        "label": "Summary",
                                                        "editable": true,
                                                        "editType": "text"
                                                },
                                                {
                                                        "field": "department",
                                                        "label": "Department",
                                                        "editable": true,
                                                        "editType": "text"
                                                },
                                                {
                                                        "field": "status",
                                                        "label": "Status",
                                                        "editable": true,
                                                        "editType": "text"
                                                }
                                        ]
                                }
                        ]
                }
        ],
        "detailRail": [
                {
                        "title": "Details",
                        "kind": "fields",
                        "fields": [
                                {
                                        "field": "code",
                                        "label": "Code"
                                },
                                {
                                        "field": "slaTargetHours",
                                        "label": "SlaTargetHours"
                                }
                        ]
                }
        ],
        "enableBulkActions": true,
        "bulkActions": [],
        "createConfig": {
                "title": "New Lab Service",
                "fields": [
                        {
                                "field": "name",
                                "label": "Name",
                                "editType": "text",
                                "required": true
                        },
                        {
                                "field": "summary",
                                "label": "Summary",
                                "editType": "text",
                                "required": true
                        },
                        {
                                "field": "department",
                                "label": "Department",
                                "editType": "select",
                                "editOptions": [
                                        {
                                                "value": "imaging",
                                                "label": "Imaging"
                                        },
                                        {
                                                "value": "diagnostic-procedures",
                                                "label": "Diagnostic Procedures"
                                        },
                                        {
                                                "value": "sample-collection",
                                                "label": "Sample Collection"
                                        },
                                        {
                                                "value": "back-office",
                                                "label": "Back Office"
                                        }
                                ],
                                "required": true
                        },
                        {
                                "field": "code",
                                "label": "Code",
                                "editType": "text",
                                "required": true
                        },
                        {
                                "field": "slaTargetHours",
                                "label": "SlaTargetHours",
                                "editType": "number",
                                "required": true
                        }
                ]
        }
} as Parameters<typeof LveWorkspace>[0])}
          callbacks={{ onViewChange: (mode) => setLveListMode(mode === "list") }}
        /></div>
      </CanvasLayout>
  );
}
