"use client";
// Module: DWS.07.M04 — Sample Collection
// Shell: SH.01  Journey stage: 1
// Layout: collection-grid
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { useRouter } from "next/navigation";
import { CatalogueLayout } from "@dbp/shell-transaction/layouts";
import CatalogGrid from "@dbp/organisms/catalog-grid";

export default function SampleCollectionPage() {
  const router = useRouter();
  return (
      <CatalogueLayout
      >
        <CatalogGrid
          key="sample-collection-catalogue"
          {...({
        "entityType": "lab-service",
        "headline": "Sample Collection.",
        "lede": "Phlebotomy and specimen intake requests.",
        "filters": {
                "department": "sample-collection"
        },
        "cardFields": {
                "title": "name",
                "description": "summary",
                "typeLabel": "department",
                "status": "status",
                "statusTone": "success",
                "footerId": "code"
        },
        "filterFields": [
                {
                        "field": "status",
                        "label": "Status"
                }
        ]
} as Parameters<typeof CatalogGrid>[0])}
          onCardClick={(_t, id) => router.push("/marketplace/deploy/" + encodeURIComponent(id))}
        />
      </CatalogueLayout>
  );
}
