"use client";
// Module: DWS.07.S44 — Organisation Setup
// Shell: SH.02  Journey stage: 2
// Layout: config-form-tabs
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { ConfigTabsLayout } from "@dbp/shell-transaction/layouts";
import { AdminSettingsForm } from "@dbp/ui";
import type { AdminSettingsFormField } from "@dbp/ui";

export default function OrganisationSetupPage() {
  return (
      <ConfigTabsLayout
        defaultTab="general"
        tabs={[
        {
          id: "general",
          label: "General",
          formId: "org-general",
          saveLabel: "Save changes",
          content: (
            <AdminSettingsForm formId="org-general" fields={[
          {
                    "name": "org-name",
                    "label": "Organisation name",
                    "fieldType": "text"
          },
          {
                    "name": "display-name",
                    "label": "Display name",
                    "fieldType": "text"
          },
          {
                    "name": "timezone",
                    "label": "Timezone",
                    "fieldType": "select",
                    "defaultValue": "Asia/Riyadh",
                    "options": [
                              {
                                        "value": "Asia/Riyadh",
                                        "label": "Asia/Riyadh"
                              },
                              {
                                        "value": "Asia/Dubai",
                                        "label": "Asia/Dubai"
                              },
                              {
                                        "value": "Europe/London",
                                        "label": "Europe/London"
                              },
                              {
                                        "value": "UTC",
                                        "label": "UTC"
                              }
                    ]
          }
] as AdminSettingsFormField[]} />
          ),
        },
        {
          id: "branding",
          label: "Branding",
          formId: "org-branding",
          saveLabel: "Save changes",
          content: (
            <AdminSettingsForm formId="org-branding" fields={[
          {
                    "name": "logo-url",
                    "label": "Logo URL",
                    "fieldType": "url"
          },
          {
                    "name": "primary-colour",
                    "label": "Primary colour (hex)",
                    "fieldType": "text"
          }
] as AdminSettingsFormField[]} />
          ),
        },
        {
          id: "billing",
          label: "Billing",
          formId: "org-billing",
          saveLabel: "Save changes",
          content: (
            <AdminSettingsForm formId="org-billing" fields={[
          {
                    "name": "plan",
                    "label": "Plan",
                    "fieldType": "select",
                    "defaultValue": "growth",
                    "options": [
                              {
                                        "value": "starter",
                                        "label": "Starter"
                              },
                              {
                                        "value": "growth",
                                        "label": "Growth"
                              },
                              {
                                        "value": "enterprise",
                                        "label": "Enterprise"
                              }
                    ]
          },
          {
                    "name": "billing-email",
                    "label": "Billing email",
                    "fieldType": "email"
          }
] as AdminSettingsFormField[]} />
          ),
        },
        {
          id: "locales",
          label: "Locales",
          formId: "org-locales",
          saveLabel: "Save changes",
          content: (
            <AdminSettingsForm formId="org-locales" fields={[
          {
                    "name": "default-language",
                    "label": "Default language",
                    "fieldType": "select",
                    "defaultValue": "en",
                    "options": [
                              {
                                        "value": "en",
                                        "label": "English"
                              },
                              {
                                        "value": "ar",
                                        "label": "Arabic"
                              }
                    ]
          },
          {
                    "name": "date-format",
                    "label": "Date format",
                    "fieldType": "select",
                    "defaultValue": "dd-mm-yyyy",
                    "options": [
                              {
                                        "value": "dd-mm-yyyy",
                                        "label": "DD/MM/YYYY"
                              },
                              {
                                        "value": "mm-dd-yyyy",
                                        "label": "MM/DD/YYYY"
                              },
                              {
                                        "value": "iso",
                                        "label": "ISO"
                              }
                    ]
          }
] as AdminSettingsFormField[]} />
          ),
        }
        ]}
      />
  );
}
