"use client";
// Catalogue listing request — APP.F22 for DWS.07.M02 (Imaging & Radiology).
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import * as React from "react";
import { useParams, useRouter } from "next/navigation";
import { toast } from "@dbp/ui";
import SubmitRequestForm from "@dbp/organisms/service-offering-request";

export default function ImagingRadiologyRequestPage() {
  const params = useParams<{ id: string }>();
  const router = useRouter();
  const id = typeof params?.id === "string" ? params.id : "";

  function handleSuccess(requestId: string) {
    toast({ title: "Request submitted", description: `Reference: ${requestId}` });
    router.push(`/marketplace/discern/${id}`);
  }

  return (
    <div className="mx-auto max-w-lg py-8">
      <SubmitRequestForm
        serviceId={id}
        onSuccess={handleSuccess}
        onCancel={() => router.push(`/marketplace/discern/${id}`)}
      />
    </div>
  );
}
