"use client";
// Admin builder detail — DWS.07.S64 (Data Flows).
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { useParams } from "next/navigation";
import { BuilderLayout } from "@dbp/shell-transaction/layouts";
import EntityDetail from "@dbp/organisms/entity-detail";

// Single-header rule (ADR-0034): EntityDetail's own EntityHeader renders the
// record's title/status below, so no page-level header is rendered at all —
// the top-bar breadcrumb (AppChrome, always rendered) is the ONLY breadcrumb
// (Shell v3.1 / N29; a second full PageHeader with a second title, or a
// second breadcrumb bar, would double-stack). The "Details" section below is
// also relabelled "Record Fields" so it doesn't repeat the "Details" tab
// label EntityDetail already renders (showActivity's Details/Activity tabs).
// N36: EntityHeader also overrides the top-bar breadcrumb's terminal crumb
// with the loaded record's name once it resolves (useBreadcrumbOverride).
export default function DataFlowsDetailPage() {
  const params = useParams<{ id: string }>();
  const id = typeof params?.id === "string" ? params.id : "";
  return (
    <BuilderLayout>
      <EntityDetail
        entityType="demo-record"
        entityId={id}
        header={{ titleField: "name", statusField: "status" }}
        sections={[
          {
            title: "Record Fields",
            fields: [
              { field: "status", label: "Status", format: "badge" },
              { field: "priority", label: "Priority", format: "badge" },
              { field: "owner", label: "Owner" },
              { field: "category", label: "Category" },
              { field: "updated", label: "Last Modified", format: "date" },
            ],
          },
        ]}
        showActivity={true}
      />
    </BuilderLayout>
  );
}
