"use client";
// Module: DWS.07.S53 — Authentication Settings
// Shell: SH.02  Journey stage: 2
// Layout: config-form-tabs
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { ConfigTabsLayout } from "@dbp/shell-transaction/layouts";
import { AdminSettingsForm } from "@dbp/ui";
import type { AdminSettingsFormField } from "@dbp/ui";

export default function AuthenticationSettingsPage() {
  return (
      <ConfigTabsLayout
        defaultTab="general"
        tabs={[
        {
          id: "general",
          label: "General",
          formId: "auth-general",
          saveLabel: "Save changes",
          content: (
            <AdminSettingsForm formId="auth-general" fields={[
          {
                    "name": "session-timeout",
                    "label": "Session timeout (minutes)",
                    "fieldType": "number",
                    "defaultValue": "60"
          },
          {
                    "name": "max-sessions",
                    "label": "Max concurrent sessions",
                    "fieldType": "select",
                    "defaultValue": "5",
                    "options": [
                              {
                                        "value": "1",
                                        "label": "1"
                              },
                              {
                                        "value": "3",
                                        "label": "3"
                              },
                              {
                                        "value": "5",
                                        "label": "5"
                              },
                              {
                                        "value": "10",
                                        "label": "10"
                              },
                              {
                                        "value": "unlimited",
                                        "label": "Unlimited"
                              }
                    ]
          },
          {
                    "name": "require-mfa",
                    "label": "Require multi-factor authentication",
                    "fieldType": "switch",
                    "defaultChecked": true
          },
          {
                    "name": "password-complexity",
                    "label": "Enforce password complexity",
                    "fieldType": "switch",
                    "defaultChecked": true
          }
] as AdminSettingsFormField[]} />
          ),
        },
        {
          id: "oauth-2-0",
          label: "OAuth 2.0",
          formId: "auth-oauth-2-0",
          saveLabel: "Save changes",
          content: (
            <AdminSettingsForm formId="auth-oauth-2-0" fields={[
          {
                    "name": "oauth-client-id",
                    "label": "Client ID",
                    "fieldType": "text"
          },
          {
                    "name": "oauth-secret",
                    "label": "Client secret",
                    "fieldType": "password"
          },
          {
                    "name": "oauth-redirect",
                    "label": "Allowed redirect URI",
                    "fieldType": "url"
          },
          {
                    "name": "token-lifetime",
                    "label": "Access token lifetime",
                    "fieldType": "select",
                    "defaultValue": "3600",
                    "options": [
                              {
                                        "value": "900",
                                        "label": "15 min"
                              },
                              {
                                        "value": "3600",
                                        "label": "1 hour"
                              },
                              {
                                        "value": "86400",
                                        "label": "24 hours"
                              },
                              {
                                        "value": "604800",
                                        "label": "7 days"
                              }
                    ]
          }
] as AdminSettingsFormField[]} />
          ),
        },
        {
          id: "saml-2-0",
          label: "SAML 2.0",
          formId: "auth-saml-2-0",
          saveLabel: "Save changes",
          content: (
            <AdminSettingsForm formId="auth-saml-2-0" fields={[
          {
                    "name": "saml-entity-id",
                    "label": "SP Entity ID",
                    "fieldType": "text"
          },
          {
                    "name": "saml-idp-url",
                    "label": "IdP metadata URL",
                    "fieldType": "url"
          },
          {
                    "name": "saml-nameid",
                    "label": "NameID format",
                    "fieldType": "select",
                    "defaultValue": "email",
                    "options": [
                              {
                                        "value": "email",
                                        "label": "Email"
                              },
                              {
                                        "value": "persistent",
                                        "label": "Persistent"
                              },
                              {
                                        "value": "transient",
                                        "label": "Transient"
                              },
                              {
                                        "value": "unspecified",
                                        "label": "Unspecified"
                              }
                    ]
          },
          {
                    "name": "sign-requests",
                    "label": "Sign authentication requests",
                    "fieldType": "switch",
                    "defaultChecked": false
          }
] as AdminSettingsFormField[]} />
          ),
        }
        ]}
      />
  );
}
