// lib/env.ts — Validated environment variables for DWS.07.
// Generated by scaffold-solution — do not edit (run with --force to regenerate).
// Uses @t3-oss/env-nextjs to validate env vars at build time and runtime.
import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DBP_AUTH_SESSION_SECRET: z.string().min(32, "DBP_AUTH_SESSION_SECRET must be at least 32 characters"),
    DBP_IDP_PROVIDER: z.enum(["password", "ldap", "entra", "entra-external"]).default("password"),
    DATABASE_URL: z.string().url().optional(),
    // Entra ID (workforce) — used when DBP_IDP_PROVIDER=entra
    ENTRA_TENANT_ID: z.string().optional(),
    ENTRA_CLIENT_ID: z.string().optional(),
    ENTRA_CLIENT_SECRET: z.string().optional(),
    ENTRA_REDIRECT_URI: z.string().url().optional(),
    // Entra External ID (CIAM) — used when DBP_IDP_PROVIDER=entra-external
    ENTRA_EXTERNAL_TENANT_NAME: z.string().optional(),
    ENTRA_EXTERNAL_CLIENT_ID: z.string().optional(),
    ENTRA_EXTERNAL_CLIENT_SECRET: z.string().optional(),
    ENTRA_EXTERNAL_REDIRECT_URI: z.string().url().optional(),
    // LDAP / on-prem Active Directory — used when DBP_IDP_PROVIDER=ldap
    LDAP_URL: z.string().optional(),
    LDAP_BIND_DN: z.string().optional(),
    LDAP_BIND_PASSWORD: z.string().optional(),
    LDAP_BASE_DN: z.string().optional(),
    LDAP_USER_FILTER: z.string().optional(),
    // PS.NOTIF env surface — names match what @dbp/ps-notif/server/transport.ts
    // actually reads (SMTP_URL connection string + MSGRAPH_* — NOT SMTP_HOST/PORT
    // or NOTIF_MS_GRAPH_*, which nothing reads).
    NOTIF_EMAIL_TRANSPORT: z.enum(["smtp", "msgraph"]).default("smtp"),
    NOTIF_EMAIL_CAPTURE: z.coerce.boolean().optional(),
    SMTP_URL: z.string().optional(),
    SMTP_FROM: z.string().email().optional(),
    MSGRAPH_TENANT_ID: z.string().optional(),
    MSGRAPH_CLIENT_ID: z.string().optional(),
    MSGRAPH_CLIENT_SECRET: z.string().optional(),
    MSGRAPH_SENDER_UPN: z.string().optional(),
    NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
    // (GAP-BRS-5, H1 Table 3) App-level rate-limit tunables — documented, env-overridable
    // defaults (auth: 10 req/60s, other platform routes: 120 req/60s). See middleware.ts.
    DBP_RATE_LIMIT_ENABLED: z.coerce.boolean().default(true),
    DBP_RATE_LIMIT_AUTH_WINDOW_S: z.coerce.number().int().positive().default(60),
    DBP_RATE_LIMIT_AUTH_MAX: z.coerce.number().int().positive().default(10),
    DBP_RATE_LIMIT_DEFAULT_WINDOW_S: z.coerce.number().int().positive().default(60),
    DBP_RATE_LIMIT_DEFAULT_MAX: z.coerce.number().int().positive().default(120),

  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().url().optional(),
  },
  runtimeEnv: {
    DBP_AUTH_SESSION_SECRET: process.env.DBP_AUTH_SESSION_SECRET,
    DBP_IDP_PROVIDER: process.env.DBP_IDP_PROVIDER,
    DATABASE_URL: process.env.DATABASE_URL,
    ENTRA_TENANT_ID: process.env.ENTRA_TENANT_ID,
    ENTRA_CLIENT_ID: process.env.ENTRA_CLIENT_ID,
    ENTRA_CLIENT_SECRET: process.env.ENTRA_CLIENT_SECRET,
    ENTRA_REDIRECT_URI: process.env.ENTRA_REDIRECT_URI,
    ENTRA_EXTERNAL_TENANT_NAME: process.env.ENTRA_EXTERNAL_TENANT_NAME,
    ENTRA_EXTERNAL_CLIENT_ID: process.env.ENTRA_EXTERNAL_CLIENT_ID,
    ENTRA_EXTERNAL_CLIENT_SECRET: process.env.ENTRA_EXTERNAL_CLIENT_SECRET,
    ENTRA_EXTERNAL_REDIRECT_URI: process.env.ENTRA_EXTERNAL_REDIRECT_URI,
    LDAP_URL: process.env.LDAP_URL,
    LDAP_BIND_DN: process.env.LDAP_BIND_DN,
    LDAP_BIND_PASSWORD: process.env.LDAP_BIND_PASSWORD,
    LDAP_BASE_DN: process.env.LDAP_BASE_DN,
    LDAP_USER_FILTER: process.env.LDAP_USER_FILTER,
    NOTIF_EMAIL_TRANSPORT: process.env.NOTIF_EMAIL_TRANSPORT,
    NOTIF_EMAIL_CAPTURE: process.env.NOTIF_EMAIL_CAPTURE,
    SMTP_URL: process.env.SMTP_URL,
    SMTP_FROM: process.env.SMTP_FROM,
    MSGRAPH_TENANT_ID: process.env.MSGRAPH_TENANT_ID,
    MSGRAPH_CLIENT_ID: process.env.MSGRAPH_CLIENT_ID,
    MSGRAPH_CLIENT_SECRET: process.env.MSGRAPH_CLIENT_SECRET,
    MSGRAPH_SENDER_UPN: process.env.MSGRAPH_SENDER_UPN,
    NODE_ENV: process.env.NODE_ENV,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    DBP_RATE_LIMIT_ENABLED: process.env.DBP_RATE_LIMIT_ENABLED,
    DBP_RATE_LIMIT_AUTH_WINDOW_S: process.env.DBP_RATE_LIMIT_AUTH_WINDOW_S,
    DBP_RATE_LIMIT_AUTH_MAX: process.env.DBP_RATE_LIMIT_AUTH_MAX,
    DBP_RATE_LIMIT_DEFAULT_WINDOW_S: process.env.DBP_RATE_LIMIT_DEFAULT_WINDOW_S,
    DBP_RATE_LIMIT_DEFAULT_MAX: process.env.DBP_RATE_LIMIT_DEFAULT_MAX,

  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
