"use client";
// Module: DWS.07.S16 — Service Requests
// Shell: SH.02  Journey stage: 2
// Layout: object-page-detail
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import * as React from "react";
import { CanvasLayout } from "@dbp/shell-transaction/layouts";
import LveWorkspace from "@dbp/organisms/lve-workspace";

export default function ServiceRequestsPage() {
  // Track LVE view mode — feeds callbacks.onViewChange on <LveWorkspace> (ADR-0040).
  const [, setLveListMode] = React.useState(true);

  return (
      <CanvasLayout
        fullBleed
      >
        <div className="-mx-[var(--shell-gutter)] -mb-[var(--shell-gutter)] h-[calc(100%+var(--shell-gutter))] flex flex-col">
          <LveWorkspace
          key="service-operations-service-requests"
          {...({
        "entityType": "service-offering-request",
        "entityLabel": "Service Offering Request",
        "title": "Service Requests",
        "externalHeader": true,
        "columns": [
                {
                        "field": "serviceId",
                        "label": "ServiceId",
                        "sortable": true
                },
                {
                        "field": "description",
                        "label": "Description",
                        "sortable": true
                },
                {
                        "field": "urgency",
                        "label": "Urgency",
                        "sortable": true
                },
                {
                        "field": "justification",
                        "label": "Justification",
                        "sortable": true
                }
        ],
        "pageSize": 25,
        "enableSearch": true,
        "enableSort": true,
        "sortFields": [
                "serviceId",
                "description",
                "urgency",
                "justification"
        ],
        "showTabCounts": true,
        "listTabs": [
                {
                        "key": "all",
                        "label": "All",
                        "where": []
                }
        ],
        "detailMode": "list",
        "enableViewToggle": true,
        "enableRecordPager": true,
        "showSaveStatus": true,
        "header": {
                "titleField": "serviceId",
                "statusField": "status"
        },
        "detailTabs": [
                {
                        "id": "details",
                        "label": "Details",
                        "sections": [
                                {
                                        "title": "Overview",
                                        "fields": [
                                                {
                                                        "field": "serviceId",
                                                        "label": "ServiceId",
                                                        "editable": true,
                                                        "editType": "text"
                                                },
                                                {
                                                        "field": "description",
                                                        "label": "Description",
                                                        "editable": true,
                                                        "editType": "text"
                                                },
                                                {
                                                        "field": "urgency",
                                                        "label": "Urgency",
                                                        "editable": true,
                                                        "editType": "text"
                                                },
                                                {
                                                        "field": "justification",
                                                        "label": "Justification",
                                                        "editable": true,
                                                        "editType": "text"
                                                }
                                        ]
                                }
                        ]
                }
        ],
        "detailRail": [],
        "enableBulkActions": true,
        "bulkActions": [],
        "createConfig": {
                "title": "New Service Offering Request",
                "fields": [
                        {
                                "field": "serviceId",
                                "label": "ServiceId",
                                "editType": "text",
                                "required": true
                        },
                        {
                                "field": "description",
                                "label": "Description",
                                "editType": "text",
                                "required": true
                        },
                        {
                                "field": "urgency",
                                "label": "Urgency",
                                "editType": "select",
                                "editOptions": [
                                        {
                                                "value": "low",
                                                "label": "Low"
                                        },
                                        {
                                                "value": "medium",
                                                "label": "Medium"
                                        },
                                        {
                                                "value": "high",
                                                "label": "High"
                                        }
                                ],
                                "required": true
                        },
                        {
                                "field": "justification",
                                "label": "Justification",
                                "editType": "text",
                                "required": false
                        }
                ]
        }
} as Parameters<typeof LveWorkspace>[0])}
          callbacks={{ onViewChange: (mode) => setLveListMode(mode === "list") }}
        /></div>
      </CanvasLayout>
  );
}
