"use client";
// Catalogue item detail — APP.F11 (MarketplaceItemDetail) for DWS.07.M03 (Diagnostic Procedures).
// A wired catalog card on /marketplace/design navigates here.
// Layout: collection-marketplace-detail
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { useParams, useRouter } from "next/navigation";
import { CanvasLayout } from "@dbp/shell-transaction/layouts";
import MarketplaceItemDetail from "@dbp/organisms/marketplace-item-detail";

const DETAIL_CONFIG = {
  "titleField": "name",
  "summaryField": "summary",
  "breadcrumb": [
    {
      "label": "Marketplace",
      "href": "/marketplace"
    },
    {
      "label": "Diagnostic Procedures",
      "href": "/marketplace/design"
    }
  ],
  "badgeFields": [
    {
      "field": "department",
      "style": "pill"
    },
    {
      "field": "status",
      "style": "pill"
    }
  ],
  "tabs": [
    {
      "id": "overview",
      "label": "Overview"
    }
  ]
};

export default function DiagnosticProceduresDetailPage() {
  const params = useParams<{ id: string }>();
  const router = useRouter();
  const id = typeof params?.id === "string" ? params.id : "";
  return (
    <CanvasLayout
    >
      <MarketplaceItemDetail
        entityType="lab-service"
        entityId={id}
        suppressHeader={true}
        titleRowAction={{ label: "Submit Enquiry", onClick: () => router.push(`/marketplace/design/${id}/request`) }}
        onNavigate={(href) => router.push(href)}
        {...(DETAIL_CONFIG as Omit<Parameters<typeof MarketplaceItemDetail>[0], "entityType" | "entityId">)}
      />
    </CanvasLayout>
  );
}
