"use client";
// Module: DWS.07.S18 — Service Quality
// Shell: SH.02  Journey stage: 2
// Layout: object-page-detail
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { CanvasLayout } from "@dbp/shell-transaction/layouts";
import EntityList from "@dbp/organisms/entity-list";

export default function ServiceQualityPage() {
  return (
      <CanvasLayout
      >
        <EntityList
          key="service-operations-service-quality"
          {...({
        "entityType": "lab-service",
        "columns": [
                {
                        "field": "name",
                        "label": "Name",
                        "sortable": true,
                        "editable": true,
                        "editType": "text"
                },
                {
                        "field": "summary",
                        "label": "Summary",
                        "sortable": true,
                        "editable": true,
                        "editType": "text"
                },
                {
                        "field": "department",
                        "label": "Department",
                        "sortable": true,
                        "editable": true,
                        "editType": "select",
                        "editOptions": [
                                {
                                        "value": "imaging",
                                        "label": "Imaging"
                                },
                                {
                                        "value": "diagnostic-procedures",
                                        "label": "Diagnostic Procedures"
                                },
                                {
                                        "value": "sample-collection",
                                        "label": "Sample Collection"
                                },
                                {
                                        "value": "back-office",
                                        "label": "Back Office"
                                }
                        ]
                },
                {
                        "field": "status",
                        "label": "Status",
                        "sortable": true,
                        "editable": true,
                        "editType": "select",
                        "editOptions": [
                                {
                                        "value": "active",
                                        "label": "Active"
                                },
                                {
                                        "value": "draft",
                                        "label": "Draft"
                                }
                        ]
                },
                {
                        "field": "code",
                        "label": "Code",
                        "sortable": true,
                        "editable": true,
                        "editType": "text"
                },
                {
                        "field": "slaTargetHours",
                        "label": "SlaTargetHours",
                        "sortable": true,
                        "editable": true,
                        "editType": "number"
                }
        ],
        "pageSize": 15,
        "enableSearch": true,
        "listTabs": [
                {
                        "key": "all",
                        "label": "All",
                        "where": []
                },
                {
                        "key": "active",
                        "label": "Active",
                        "where": [
                                {
                                        "field": "status",
                                        "op": "is",
                                        "value": "active"
                                }
                        ]
                },
                {
                        "key": "draft",
                        "label": "Draft",
                        "where": [
                                {
                                        "field": "status",
                                        "op": "is",
                                        "value": "draft"
                                }
                        ]
                }
        ],
        "detailDrawer": {
                "titleField": "name",
                "subtitleFields": [
                        "code"
                ],
                "entityLabel": "Lab Service",
                "statusField": "status",
                "statusTones": {
                        "active": "success",
                        "draft": "info"
                },
                "codeField": "code",
                "descriptionField": "summary",
                "quickActions": [
                        {
                                "id": "mark-active",
                                "label": "Mark active",
                                "patch": {
                                        "status": "active"
                                }
                        }
                ],
                "headerMenu": [
                        {
                                "id": "mark-draft",
                                "label": "Mark draft",
                                "patch": {
                                        "status": "draft"
                                }
                        }
                ],
                "variants": {},
                "labels": {},
                "defaultSections": [
                        {
                                "id": "overview",
                                "title": "Overview",
                                "fields": [
                                        {
                                                "id": "name",
                                                "label": "Name",
                                                "format": "text",
                                                "editable": false
                                        },
                                        {
                                                "id": "summary",
                                                "label": "Summary",
                                                "format": "text",
                                                "editable": false
                                        },
                                        {
                                                "id": "department",
                                                "label": "Department",
                                                "format": "badge",
                                                "editable": false
                                        },
                                        {
                                                "id": "status",
                                                "label": "Status",
                                                "format": "text",
                                                "render": "status-dot",
                                                "badgeTones": {
                                                        "active": "success",
                                                        "draft": "info"
                                                },
                                                "editable": false
                                        },
                                        {
                                                "id": "code",
                                                "label": "Code",
                                                "format": "text",
                                                "editable": false
                                        },
                                        {
                                                "id": "slaTargetHours",
                                                "label": "SlaTargetHours",
                                                "format": "text",
                                                "editable": false
                                        }
                                ]
                        }
                ],
                "tabs": [
                        {
                                "id": "overview",
                                "label": "Overview",
                                "kind": "fields"
                        },
                        {
                                "id": "comments",
                                "label": "Comments",
                                "kind": "comments"
                        },
                        {
                                "id": "audit",
                                "label": "Audit",
                                "kind": "audit"
                        }
                ],
                "comments": {
                        "entityType": "lab-service"
                },
                "deepLink": true,
                "expandable": true
        }
} as Parameters<typeof EntityList>[0])}
        />
      </CanvasLayout>
  );
}
