"use client";
// Module: DWS.07.S50 — User Management
// Shell: SH.02  Journey stage: 2
// Layout: collection-table
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { CanvasLayout } from "@dbp/shell-transaction/layouts";
import { AdminUserList } from "@dbp/organisms/admin-user-list";
import { DEMO_IDENTITIES } from "../../../../solution/fixtures/demo-identities";

export default function UserManagementPage() {
  return (
      <CanvasLayout>
        <AdminUserList users={DEMO_IDENTITIES.map((entry) => entry.user)} />
      </CanvasLayout>
  );
}
