"use client";
// Module: DWS.07.S48 — Business Hours
// Shell: SH.02  Journey stage: 2
// Layout: config-form-single
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { SettingsLayout } from "@dbp/shell-transaction/layouts";
import { Button } from "@dbp/ui";
import { AdminSettingsForm } from "@dbp/ui";
import type { AdminSettingsFormSection } from "@dbp/ui";
import { SettingsNav } from "@dbp/ui";

export default function BusinessHoursPage() {
  return (
      <SettingsLayout
        nav={<SettingsNav links={[{"href":"/admin/organisation","label":"Organisation Setup"},{"href":"/admin/workspace-settings","label":"Workspace Settings"},{"href":"/admin/branding","label":"Branding"},{"href":"/admin/regional","label":"Regional & Language"},{"href":"/admin/business-hours","label":"Business Hours"},{"href":"/admin/defaults","label":"Default Values"},{"href":"/admin/users","label":"User Management"},{"href":"/admin/roles","label":"Role Management"},{"href":"/admin/access-control","label":"Access Control"},{"href":"/admin/auth","label":"Authentication Settings"},{"href":"/admin/form-builder","label":"Form Builder"},{"href":"/admin/workflow-builder","label":"Workflow Builder"},{"href":"/admin/rules","label":"Rule Management"},{"href":"/admin/data-model","label":"Data Model"},{"href":"/admin/master-data","label":"Master Data"},{"href":"/admin/reference-data","label":"Reference Data"},{"href":"/admin/data-quality","label":"Data Quality Rules"},{"href":"/admin/data-lineage","label":"Data Lineage"},{"href":"/admin/apis","label":"API Management"},{"href":"/admin/connectors","label":"Connectors"},{"href":"/admin/data-flows","label":"Data Flows"},{"href":"/admin/data-import","label":"Data Import"},{"href":"/admin/policies","label":"Policy Management"},{"href":"/admin/controls","label":"Control Register"},{"href":"/admin/risks","label":"Risk Register"},{"href":"/admin/security-logs","label":"Security Logs"}]} />}
      >
        <div className="flex justify-end gap-2 mb-4">
          <Button variant="navy" onClick={() => (document.getElementById("admin-business-hours") as HTMLFormElement | null)?.requestSubmit()}>Save changes</Button>
        </div>
        <AdminSettingsForm formId="admin-business-hours" sections={[
        {
                "title": "Business hours",
                "fields": [
                        {
                                "name": "working-days",
                                "label": "Working days",
                                "fieldType": "select",
                                "defaultValue": "sun-thu",
                                "options": [
                                        {
                                                "value": "sun-thu",
                                                "label": "Sunday – Thursday"
                                        },
                                        {
                                                "value": "mon-fri",
                                                "label": "Monday – Friday"
                                        }
                                ]
                        },
                        {
                                "name": "day-start",
                                "label": "Day start",
                                "fieldType": "text",
                                "placeholder": "08:00"
                        },
                        {
                                "name": "day-end",
                                "label": "Day end",
                                "fieldType": "text",
                                "placeholder": "17:00"
                        },
                        {
                                "name": "observe-public-holidays",
                                "label": "Observe public holidays",
                                "fieldType": "switch",
                                "defaultChecked": true
                        }
                ]
        }
] as AdminSettingsFormSection[]} />
      </SettingsLayout>
  );
}
