"use client";
// Module: DWS.07.S52 — Access Control
// Shell: SH.02  Journey stage: 2
// Layout: collection-table
// Body-only page — TransactionShell provided by app/(authenticated)/layout.tsx
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { CanvasLayout } from "@dbp/shell-transaction/layouts";
import { AdminAccessMatrix } from "@dbp/organisms/admin-access-matrix";

export default function AccessControlPage() {
  return (
      <CanvasLayout>
        <AdminAccessMatrix />
      </CanvasLayout>
  );
}
