"use client";
// AI Cockpit — auto-emitted placeholder (no manifest.copilot block configured).
// Generated by scaffold-solution — do not edit (run with --force to regenerate)
import { CanvasLayout } from "@dbp/shell-transaction/layouts";
import { PageHeader } from "@dbp/ui";

export default function CopilotPage() {
  return (
    <CanvasLayout header={<PageHeader title="AI Cockpit" />}>
      <p className="text-sm text-[var(--color-text-muted)]">Configure a <code>copilot:</code> block in SOLUTION.md to enable this feature.</p>
    </CanvasLayout>
  );
}
